redhand: redhand::game_object Class Reference
redhand::game_object Class Reference
The game_object is a simple object which can be displayed in a world.
#include <game_object.hpp>
Public Member Functions
game_object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader *attached_shader, int gl_drawing_mode)
Construct a new game object object.
game_object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader *attached_shader, int gl_drawing_mode, std::string name)
Construct a new game object object.
game_object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader *attached_shader, int gl_drawing_mode, std::function< void(shader *)> routine)
Construct a new game object object.
game_object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader *attached_shader, int gl_drawing_mode, std::vector< float > scaler, float rotator, std::vector< float > postitions)
Construct a new game object object.
game_object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader *attached_shader, int gl_drawing_mode, std::function< void(shader *)> routine, std::vector< float > scaler, float rotator, std::vector< float > postitions)
Construct a new game object object.
game_object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader *attached_shader, int gl_drawing_mode, std::function< void(shader *)> routine, std::vector< float > scaler, float rotator, std::vector< float > postitions, texture2D *texture)
Construct a new game object object.
game_object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader *attached_shader, int gl_drawing_mode, std::function< void(shader *)> routine, std::vector< float > scaler, float rotator, std::vector< float > postitions, texture2D *texture, std::vector< float > texels)
Construct a new game object object.
~game_object ()
Destroy the game object.
void setShaderRoutine (std::function< void(shader *)> routine)
This function sets the shader routine to the given function.
void setLoopFunction (std::function< void(GLFWwindow *window, game_object *obj)> loop)
This function sets the loop function to the given function.
shader * getShader ()
This function returns a pointer to the attached shader.
void draw ()
This function draws the object on the screen.
void onLoop (GLFWwindow *window)
The loop function of the object.
bool hasErrord ()
false if no error has happened
std::vector< float > getPosition ()
Get the Position of the object.
void setPosition (std::vector< float > pos)
Set the Position of the object.
void move (std::vector< float > delta_pos)
moves the object by the specified amount
float getRotation ()
gets the rotation in degrees
void setRotation (float rot)
sets the objects rotation by the specified amount in degrees counterclockwise
void rotate (float delta_rot)
Rotates the object by the specified amount in degrees counterclockwise.
void setColorAlpha (float alpha)
set the alpha value of the color
void setScreenSize (int width, int height)
Sets the screen size to let the object scale the texture correctly.
void setName (std::string name)
This function sets the name of the game_object to the given string.
std::string getName ()
This funtion returns the name of the object.
std::vector< float > getScale ()
get the scal of the object
Private Attributes
unsigned int VAO
The identifier of the Video Array Object.
unsigned int VBO
The identifier of the Video Buffer Object.
unsigned int EBO
The identifier of the Element Buffer Object.
int indices_size
This is 3 * "number of tirangle" and is important to actually draw those triangles.
shader * object_shader
The attaced shader.
texture2D * object_texture
The attached texture.
unsigned int textureMode = 0
The texture mode of the object.
float colorAlphaValue = 1.0f
The alpha value of the color.
bool errored = false
false if no error happened
std::function< void(shader *)> shader_routine
A custom function which is called just after the shader is activated.
std::function< void(GLFWwindow *window, game_object *obj)> LoopFunction
A function that will be called once every tick.
std::vector< float > object_position = {0.0f, 0.0f}
The position of the object in World Coordinates.
std::shared_mutex positionLock
lock the position of the object
std::vector< float > object_scale = {1.0f, 1.0f}
The scale of the object in World scale.
std::shared_mutex scaleLock
lock the scale of the object
float object_rotation = 0.0f
The rotation of the object in degrees.
std::shared_mutex rotationLock
lock the rotation of the object
glm::vec2 texture_scale = glm::vec2(1.0f, 1.0f)
the scale of the texture attached to this object
std::shared_mutex textureScaleLock
lock the texture scale of the object
std::string object_name = "game_object"
The name of the object.
std::shared_mutex nameLock
lock the name of the object
std::shared_mutex gameObjectLock
The lock for the object.
Detailed Description
The game_object is a simple object which can be displayed in a world.
It is the first abstraction layer and is a very low level openGL object. You can create a game_object by specifying all the points, and which points form a triangel. Each game_object NEEDS a shader in order to work. Please use a shader which is added to the same world as the game_object in order to prevent errors.
The Points specified are all local coordinates. This means they are in the first sector of a 2 dimensional coordinate system. If there is any point outside of this range the creation of the object will fail. For each point you must also specify the color of that point.
Each game_object has a name which is "game_object" by default.
In addition to that the object also holds its position, rotation and scale in world coordinates.
Definition at line 38 of file game_object.hpp.
Constructor & Destructor Documentation
game_object() [1/7]
redhand::game_object::game_object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader * attached_shader, int gl_drawing_mode)
Construct a new game object object.
Parameters
points An array with all the points this object has in local coordinates
indices The indicies which specifiy, which points form a triangle
colors The color of the points
attached_shader A pointer to the attached shader
Note
the shader should be added to the same world
Parameters
gl_drawing_mode The drawing mode of the game_object
Create arrays and buffers
Definition at line 6 of file game_object.cpp.
  {
     object_shader = attached_shader;
     if(object_shader == nullptr || object_shader == NULL){
         errored = true;
     }else{
         for(int i = 0; i < points.size(); i++){
             if(points.at(i) < 0.0f || points.at(i) > 1.0f){
                 errored = true;
                 break;
             }
         }
     }
     if(!errored){
         shader_routine = [](shader*){};
         LoopFunction = [](GLFWwindow*, game_object*){};
         int point_size = (int)(1.5f * points.size());
         int colors_size = colors.size();
         int texels_size = points.size();
         indices_size = indices.size();
         std::vector <float> data;
         for(int i = 0; i < points.size();i++){
             data.emplace_back(points.at(i));
             if(i % 2 == 1){
                 data.emplace_back(points.at(0.0f));
             }
         }
         data.insert(data.end(), colors.begin(), colors.end());
         data.insert(data.end(), points.begin(), points.end());
         //Initilize the buffers
         glGenVertexArrays(1, &VAO);
         glGenBuffers(1, &VBO);
         glGenBuffers(1, &EBO);
         glBindVertexArray(VAO);
         glBindBuffer(GL_ARRAY_BUFFER, VBO);
         glBufferData(GL_ARRAY_BUFFER, sizeof(float)*data.size(), data.data(), gl_drawing_mode);
         glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, EBO);
         glBufferData(GL_ARRAY_BUFFER, sizeof(float)*data.size(), data.data(), gl_drawing_mode);
         glBufferData(GL_ELEMENT_ARRAY_BUFFER, sizeof(int)*indices.size(), indices.data(), gl_drawing_mode);
         glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 3 * sizeof(float), (void*)0);
         glEnableVertexAttribArray(0);
         glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, 3 * sizeof(float), (void*)(point_size * sizeof(float)));
         glEnableVertexAttribArray(1);
         glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, 2 * sizeof(float), (void*)((point_size + colors_size) * sizeof(float)));
         glEnableVertexAttribArray(2);
     }
 }
game_object() [2/7]
redhand::game_object::game_object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader * attached_shader, int gl_drawing_mode, std::string name)
Construct a new game object object.
Parameters
points An array with all the points this object has in local coordinates
indices The indicies which specifiy, which points form a triangle
colors The color of the points
attached_shader A pointer to the attached shader
Note
the shader should be added to the same world
Parameters
gl_drawing_mode The drawing mode of the game_object
Definition at line 74 of file game_object.cpp.
References object_name.
                        :game_object(points, indices, colors, attached_shader, gl_drawing_mode){
             object_name = name;
         }
game_object() [3/7]
redhand::game_object::game_object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader * attached_shader, int gl_drawing_mode, std::function< void(shader *)> routine)
Construct a new game object object.
Parameters
points An array with all the points this object has in local coordinates
indices The indicies which specifiy, which points form a triangle
colors The color of the points
attached_shader A pointer to the attached shader
Note
the shader should be added to the same world
Parameters
gl_drawing_mode The drawing mode of the game_object
routine The shader routine which should be used
Definition at line 85 of file game_object.cpp.
References shader_routine.
  :game_object(points,indices,colors,attached_shader,gl_drawing_mode){
     shader_routine = routine;
 }
game_object() [4/7]
redhand::game_object::game_object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader * attached_shader, int gl_drawing_mode, std::vector< float > scaler, float rotator, std::vector< float > postitions)
Construct a new game object object.
Parameters
points An array with all the points this object has in local coordinates
indices The indicies which specifiy, which points form a triangle
colors The color of the points
attached_shader A pointer to the attached shader
Note
the shader should be added to the same world
Parameters
gl_drawing_mode The drawing mode of the game_object
scaler The scale of the object in world coordinates
rotator The rotation of the object in world coordinates
postitions The position of the object in world coordinates
Definition at line 98 of file game_object.cpp.
References object_position, object_rotation, and object_scale.
  :game_object(points, indices, colors, attached_shader, gl_drawing_mode){
     object_scale = scaler;
     object_rotation = rotator;
     if (postitions.size() != 2){
         object_position = {0.0f, 0.0f};
     }else{
         object_position = postitions;
     }
 }
game_object() [5/7]
redhand::game_object::game_object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader * attached_shader, int gl_drawing_mode, std::function< void(shader *)> routine, std::vector< float > scaler, float rotator, std::vector< float > postitions)
Construct a new game object object.
Parameters
points An array with all the points this object has in local coordinates
indices The indicies which specifiy, which points form a triangle
colors The color of the points
attached_shader A pointer to the attached shader
Note
the shader should be added to the same world
Parameters
gl_drawing_mode The drawing mode of the game_object
routine The shader routine which should be used
scaler The scale of the object in world coordinates
rotator The rotation of the object in world coordinates
postitions The position of the object in world coordinates
Definition at line 120 of file game_object.cpp.
References object_position, object_rotation, and object_scale.
  :game_object(points, indices, colors, attached_shader, gl_drawing_mode,routine){
     object_scale = scaler;
     object_rotation = rotator;
     if (postitions.size() != 2){
         object_position = {0.0f, 0.0f};
     }
     object_position = postitions;
 }
game_object() [6/7]
redhand::game_object::game_object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader * attached_shader, int gl_drawing_mode, std::function< void(shader *)> routine, std::vector< float > scaler, float rotator, std::vector< float > postitions, texture2D * texture)
Construct a new game object object.
Parameters
points An array with all the points this object has in local coordinates
indices The indicies which specifiy, which points form a triangle
colors The color of the points
attached_shader A pointer to the attached shader
Note
the shader should be added to the same world
Parameters
gl_drawing_mode The drawing mode of the game_object
routine The shader routine which should be used
scaler The scale of the object in world coordinates
rotator The rotation of the object in world coordinates
postitions The position of the object in world coordinates
texture A pointer to the attaches texture
Definition at line 142 of file game_object.cpp.
References redhand::texture2D::hasErrord(), object_texture, and textureMode.
  :game_object(points, indices, colors, attached_shader, gl_drawing_mode,routine,scaler,rotator,postitions){
     if (texture != NULL && texture != nullptr && !texture->hasErrord()){
         textureMode = 1;
         object_texture = texture;
     }
 }
game_object() [7/7]
redhand::game_object::game_object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader * attached_shader, int gl_drawing_mode, std::function< void(shader *)> routine, std::vector< float > scaler, float rotator, std::vector< float > postitions, texture2D * texture, std::vector< float > texels)
Construct a new game object object.
Parameters
points An array with all the points this object has in local coordinates
indices The indicies which specifiy, which points form a triangle
colors The color of the points
attached_shader A pointer to the attached shader
Note
the shader should be added to the same world
Parameters
gl_drawing_mode The drawing mode of the game_object
routine The shader routine which should be used
scaler The scale of the object in world coordinates
rotator The rotation of the object in world coordinates
postitions The position of the object in world coordinates
texture A pointer to the attaches texture
texels A Vector containing the texture coordinates
Create arrays and buffers
Definition at line 164 of file game_object.cpp.
References EBO, errored, redhand::texture2D::hasErrord(), indices_size, LoopFunction, object_position, object_rotation, object_scale, object_shader, object_texture, shader_routine, textureMode, VAO, and VBO.
  {
     object_shader = attached_shader;
     if(object_shader == nullptr || object_shader == NULL ){
         errored = true;
     }else{
         for(int i = 0; i < points.size(); i++){
             if(points.at(i) < 0.0f || points.at(i) > 1.0f){
                 errored = true;
                 break;
             }
         }
     }
     if(!errored){
         shader_routine = [](shader*){};
         LoopFunction = [](GLFWwindow*, game_object*){};
         int point_size = (int)(1.5f * points.size());
         int colors_size = colors.size();
         int texels_size = points.size();
         if(texels.size() != 0 && texels.size() == points.size()){
             texels_size = texels.size();
         }
         indices_size = indices.size();
         std::vector <float> data;
         for(int i = 0; i < points.size();i++){
             data.emplace_back(points.at(i));
             if(i % 2 == 1){
                 data.emplace_back(points.at(0.0f));
             }
         }
         data.insert(data.end(),colors.begin(),colors.end());
         if(texels.size() != 0 && texels.size() == points.size()){
             data.insert(data.end(),texels.begin(),texels.end());
         }else{
             data.insert(data.end(),points.begin(),points.end());
         }
         //Initilize the buffers
         glGenVertexArrays(1, &VAO);
         glGenBuffers(1, &VBO);
         glGenBuffers(1, &EBO);
         glBindVertexArray(VAO);
         glBindBuffer(GL_ARRAY_BUFFER, VBO);
         glBufferData(GL_ARRAY_BUFFER, sizeof(float)*data.size(), data.data(), gl_drawing_mode);
         glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, EBO);
         glBufferData(GL_ARRAY_BUFFER, sizeof(float)*data.size(), data.data(), gl_drawing_mode);
         glBufferData(GL_ELEMENT_ARRAY_BUFFER, sizeof(int)*indices.size(), indices.data(), gl_drawing_mode);
         glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 3 * sizeof(float), (void*)0);
         glEnableVertexAttribArray(0);
         glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, 3 * sizeof(float), (void*)(point_size * sizeof(float)));
         glEnableVertexAttribArray(1);
         glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, 2 * sizeof(float), (void*)((point_size + colors_size) * sizeof(float)));
         glEnableVertexAttribArray(2);
         shader_routine = routine;
         object_rotation = rotator;
         object_scale = scaler;
         if (postitions.size() != 2){
             object_position = {0.0f, 0.0f};
         }else{
             object_position = postitions;
         }
         if (texture != NULL && texture != nullptr && !texture->hasErrord()){
             textureMode = 1;
             object_texture = texture;
         }
     }
 }
~game_object()
redhand::game_object::~game_object ()
Destroy the game object.
Definition at line 265 of file game_object.cpp.
References EBO, gameObjectLock, nameLock, positionLock, rotationLock, scaleLock, textureScaleLock, VAO, and VBO.
{
     auto lock = std::scoped_lock(gameObjectLock,nameLock,positionLock,rotationLock,textureScaleLock,scaleLock);
     try{
         glDeleteVertexArrays(1, &VAO);
         glDeleteBuffers(1, &VBO);
         glDeleteBuffers(1, &EBO);
     }
     catch(const std::exception& e){
         std::cerr << e.what() << '\n';
     }
 }
Member Function Documentation
draw()
void redhand::game_object::draw ()
This function draws the object on the screen.
Definition at line 285 of file game_object.cpp.
References redhand::texture2D::bind(), colorAlphaValue, gameObjectLock, redhand::shader::getID(), getPosition(), getRotation(), getScale(), indices_size, object_shader, object_texture, redhand::shader::setFloat(), redhand::shader::setInt(), redhand::shader::setTextureScale(), shader_routine, texture_scale, textureMode, redhand::shader::use(), and VAO.
{
     auto lock = std::shared_lock(gameObjectLock);
     //if there are textures set the texture scale of the shader
     if(textureMode == 1){
         object_shader->setTextureScale(texture_scale);
     }
     //enable texture shader
     object_shader->use();
     //set the uniform variables
     object_shader->setInt("textureMode", textureMode);
     object_shader->setFloat("colorAlpha", colorAlphaValue);
     //bind texture and draw background
     if(textureMode == 1){
         object_texture->bind(0);
     }
     //Create World transformation matrix
     glm::mat4 worldTrans = glm::mat4(1.0f);
     worldTrans = glm::translate(worldTrans, glm::vec3(getPosition().at(0),getPosition().at(1),0.0f));
     worldTrans = glm::rotate(worldTrans, glm::radians(getRotation()), glm::vec3(0.0f, 0.0f, 1.0f));
     worldTrans = glm::scale(worldTrans, glm::vec3(getScale().at(0), getScale().at(1), 1.0f));
     unsigned int transformLoc = glGetUniformLocation(object_shader->getID(), "worldTransformation");
     glUniformMatrix4fv(transformLoc, 1, GL_FALSE, glm::value_ptr(worldTrans));
     //run the custom shader routine
     shader_routine(object_shader);
     //actually draw the object
     glBindVertexArray(VAO);
     glDrawElements(GL_TRIANGLES, indices_size, GL_UNSIGNED_INT, 0);
     //reset the uniform values just in case
     object_shader->setInt("textureMode", 0);
     object_shader->setFloat("colorAlpha", 1.0f);
 }
getName()
std::string redhand::game_object::getName ()
This funtion returns the name of the object.
Definition at line 421 of file game_object.cpp.
References nameLock, and object_name.
{
     std::shared_lock<std::shared_mutex> lock(nameLock);
     return object_name;
 }
getPosition()
std::vector< float > redhand::game_object::getPosition ()
Get the Position of the object.
Returns
std::vector<float>
Definition at line 359 of file game_object.cpp.
References object_position, and positionLock.
{
     std::shared_lock<std::shared_mutex> lock(positionLock);
     return object_position;
 };
getRotation()
float redhand::game_object::getRotation ()
gets the rotation in degrees
Definition at line 377 of file game_object.cpp.
References object_rotation, and rotationLock.
{
     std::shared_lock<std::shared_mutex> lock(rotationLock);
     return object_rotation;
 };
getScale()
std::vector< float > redhand::game_object::getScale ()
get the scal of the object
Returns
std::vector<float> [0] = x scale and [1] is y scale
Definition at line 381 of file game_object.cpp.
References object_scale, and scaleLock.
{
     std::shared_lock<std::shared_mutex> lock(scaleLock);
     return object_scale;
 };
getShader()
shader * redhand::game_object::getShader ()
This function returns a pointer to the attached shader.
Definition at line 354 of file game_object.cpp.
References gameObjectLock, and object_shader.
{
     std::shared_lock<std::shared_mutex> lock(gameObjectLock);
     return object_shader;
 };
hasErrord()
bool redhand::game_object::hasErrord ()
false if no error has happened
Definition at line 328 of file game_object.cpp.
References errored, and gameObjectLock.
{
     std::shared_lock<std::shared_mutex> lock(gameObjectLock);
     return errored;
 }
move()
void redhand::game_object::move (std::vector< float > delta_pos)
moves the object by the specified amount
Parameters
delta_pos a vector with the difference in x and y direction in world scale
Definition at line 369 of file game_object.cpp.
References object_position, and positionLock.
{
     if(delta_pos.size() == 2){
         std::scoped_lock<std::shared_mutex> lock(positionLock);
         object_position.at(0) += delta_pos.at(0);
         object_position.at(1) += delta_pos.at(1);
     }
 };
onLoop()
void redhand::game_object::onLoop (GLFWwindow * window)
The loop function of the object.
Definition at line 340 of file game_object.cpp.
References gameObjectLock, and LoopFunction.
{
     std::shared_lock<std::shared_mutex> lock(gameObjectLock);
     LoopFunction(window, this);
 };
rotate()
void redhand::game_object::rotate (float delta_rot)
Rotates the object by the specified amount in degrees counterclockwise.
Parameters
the difference in rotation in degrees
Definition at line 397 of file game_object.cpp.
References object_rotation, and rotationLock.
{
     while(delta_rot >= 360.0f){
         delta_rot -= 360.0f;
     }
     while(delta_rot < 0.0f){
         delta_rot += 360.0f;
     }
     std::scoped_lock<std::shared_mutex> lock(rotationLock);
     object_rotation += delta_rot;
     if(object_rotation >= 360.0f){
         object_rotation -= 360.0f;
     }
     if(object_rotation < 0.0f){
         object_rotation += 360.0f;
     }
 };
setColorAlpha()
void redhand::game_object::setColorAlpha (float alpha)
set the alpha value of the color
Parameters
alpha The new alpha value of the color
Definition at line 333 of file game_object.cpp.
References colorAlphaValue, and gameObjectLock.
{
     if(alpha >= 0.0f && alpha <= 1.0f){
         std::scoped_lock<std::shared_mutex> lock(gameObjectLock);
         colorAlphaValue = alpha;
     }
 }
setLoopFunction()
void redhand::game_object::setLoopFunction (std::function< void(GLFWwindow *window, game_object *obj)> loop)
This function sets the loop function to the given function.
Definition at line 349 of file game_object.cpp.
References gameObjectLock, and LoopFunction.
{
     std::scoped_lock<std::shared_mutex> lock(gameObjectLock);
     LoopFunction = loop;
 };
setName()
void redhand::game_object::setName (std::string name)
This function sets the name of the game_object to the given string.
Definition at line 417 of file game_object.cpp.
References nameLock, and object_name.
{
     std::scoped_lock<std::shared_mutex> lock(nameLock);
     object_name = name;
 }
setPosition()
void redhand::game_object::setPosition (std::vector< float > pos)
Set the Position of the object.
Parameters
pos a vector with the in x and y direction in world scale
Definition at line 364 of file game_object.cpp.
References object_position, and positionLock.
{
     std::scoped_lock<std::shared_mutex> lock(positionLock);
     object_position = pos;
 };
setRotation()
void redhand::game_object::setRotation (float rot)
sets the objects rotation by the specified amount in degrees counterclockwise
Parameters
rot the new rotation in degrees
Definition at line 385 of file game_object.cpp.
References object_rotation, and rotationLock.
{
     while(rot >= 360.0f){
         rot -= 360.0f;
     }
     while(rot < 0.0f){
         rot += 360.0f;
     }
     std::scoped_lock<std::shared_mutex> lock(rotationLock);
     object_rotation = rot;
 };
setScreenSize()
void redhand::game_object::setScreenSize (int width, int height)
Sets the screen size to let the object scale the texture correctly.
Parameters
width the width of the screen
height the height of he screen
Definition at line 278 of file game_object.cpp.
References redhand::texture2D::getHeight(), redhand::texture2D::getWidth(), object_scale, object_texture, texture_scale, and textureMode.
{
     if(textureMode == 1 && object_texture != nullptr && object_texture != NULL){
         texture_scale.x = object_scale.at(0) * width / (object_texture->getWidth() * (width / height + 1.0f));
         texture_scale.y = object_scale.at(1) * height / (object_texture->getHeight() * (height / width + 1.0f));
     }
 }
setShaderRoutine()
void redhand::game_object::setShaderRoutine (std::function< void(shader *)> routine)
This function sets the shader routine to the given function.
Definition at line 345 of file game_object.cpp.
References gameObjectLock, and shader_routine.
{
     std::scoped_lock<std::shared_mutex> lock(gameObjectLock);
     shader_routine = routine;
 };
Member Data Documentation
colorAlphaValue
float redhand::game_object::colorAlphaValue = 1.0f private
The alpha value of the color.
Definition at line 63 of file game_object.hpp.
EBO
unsigned int redhand::game_object::EBO private
The identifier of the Element Buffer Object.
Definition at line 48 of file game_object.hpp.
errored
bool redhand::game_object::errored = false private
false if no error happened
Definition at line 66 of file game_object.hpp.
gameObjectLock
std::shared_mutex redhand::game_object::gameObjectLock private
The lock for the object.
Definition at line 101 of file game_object.hpp.
indices_size
int redhand::game_object::indices_size private
This is 3 * "number of tirangle" and is important to actually draw those triangles.
Definition at line 51 of file game_object.hpp.
LoopFunction
std::function<void(GLFWwindow* window, game_object* obj)> redhand::game_object::LoopFunction private
A function that will be called once every tick.
Definition at line 72 of file game_object.hpp.
nameLock
std::shared_mutex redhand::game_object::nameLock private
lock the name of the object
Definition at line 98 of file game_object.hpp.
object_name
std::string redhand::game_object::object_name = "game_object" private
The name of the object.
Definition at line 96 of file game_object.hpp.
object_position
std::vector<float> redhand::game_object::object_position = {0.0f, 0.0f} private
The position of the object in World Coordinates.
Definition at line 75 of file game_object.hpp.
object_rotation
float redhand::game_object::object_rotation = 0.0f private
The rotation of the object in degrees.
Definition at line 85 of file game_object.hpp.
object_scale
std::vector<float> redhand::game_object::object_scale = {1.0f, 1.0f} private
The scale of the object in World scale.
Definition at line 80 of file game_object.hpp.
object_shader
shader* redhand::game_object::object_shader private
The attaced shader.
Definition at line 54 of file game_object.hpp.
object_texture
texture2D* redhand::game_object::object_texture private
The attached texture.
Definition at line 57 of file game_object.hpp.
positionLock
std::shared_mutex redhand::game_object::positionLock private
lock the position of the object
Definition at line 77 of file game_object.hpp.
rotationLock
std::shared_mutex redhand::game_object::rotationLock private
lock the rotation of the object
Definition at line 87 of file game_object.hpp.
scaleLock
std::shared_mutex redhand::game_object::scaleLock private
lock the scale of the object
Definition at line 82 of file game_object.hpp.
shader_routine
std::function<void(shader*)> redhand::game_object::shader_routine private
A custom function which is called just after the shader is activated.
Definition at line 69 of file game_object.hpp.
texture_scale
glm::vec2 redhand::game_object::texture_scale = glm::vec2(1.0f, 1.0f) private
the scale of the texture attached to this object
Definition at line 90 of file game_object.hpp.
textureMode
unsigned int redhand::game_object::textureMode = 0 private
The texture mode of the object.
Definition at line 60 of file game_object.hpp.
textureScaleLock
std::shared_mutex redhand::game_object::textureScaleLock private
lock the texture scale of the object
Definition at line 92 of file game_object.hpp.
VAO
unsigned int redhand::game_object::VAO private
The identifier of the Video Array Object.
Definition at line 42 of file game_object.hpp.
VBO
unsigned int redhand::game_object::VBO private
The identifier of the Video Buffer Object.
Definition at line 45 of file game_object.hpp.
The documentation for this class was generated from the following files:
include/redhand/game_object.hpp
src/game_object.cpp