redhand: world Class Reference
world Class Reference
#include <world.hpp>
Public Member Functions
world ()
The constructor will create an empty world which can be filled with objects.
~world ()
The destructor will clean up everything and delete all objects stored in this world.
int addShader (shader *)
The addShader function will add a shader to the world.
int addTexture (texture2D *)
The addTexture function will add a texture to the world.
int addObject (game_object *)
The addObject function will add an object to the world.
int removeShader (shader *shade)
This function removes a shader from its world and delete the shader.
int removeTexture (texture2D *tex)
This function removes a texture from its world and delete the texture.
int removeObject (game_object *obj)
This function removes an object from its world and delete the object.
shader * getShaderByName (std::string name)
This function returns a pointer to the first shader with the given name.
texture2D * getTextureByName (std::string name)
This function returns a pointer to the first texture with the given name.
game_object * getObjectByName (std::string name)
This function returns a pointer to the first object with the given name.
void tick (GLFWwindow *window)
This function executes a world tick and is called for each frame.
void setCamera (float pos_x, float pos_y)
This function is used to set the position of the camera.
void moveCamera (float delta_pos_x, float delta_pos_y)
This function is used to set the position of the camera.
void setWindowSize (int width, int height)
This functions sets the window size to construct the projection matrix.
Private Attributes
std::vector< game_object * > WorldObjects
This vector holds all the game_objetcs in this world.
std::vector< shader * > WorldShaders
This vector holds all the shaders in this world.
std::vector< texture2D * > WorldTextures
This vector holds all the textures in this world.
float cameraPosition [2] = {0.0f, 0.0f}
This array holds the current camera Position.
int windowWidth = 600
This variable holds the width of the window in pixels.
int windowHeight = 200
This variable holds the height of the window in pixels.
glm::mat4 projectionMatrix
This variable holds the current projection matrix.
Detailed Description
Definition at line 7 of file world.hpp.
Constructor & Destructor Documentation
world()
world::world ()
The constructor will create an empty world which can be filled with objects.
Definition at line 3 of file world.cpp.
References setWindowSize(), WorldObjects, WorldShaders, and WorldTextures.
             {
     WorldShaders = std::vector<shader*>(0);
     WorldTextures = std::vector<texture2D*>(0);
     WorldObjects = std::vector<game_object*>(0);
     setWindowSize(600,600);
 }
~world()
world::~world ()
The destructor will clean up everything and delete all objects stored in this world.
Definition at line 11 of file world.cpp.
References WorldObjects, WorldShaders, and WorldTextures.
              {
     //delete objects
     try{
         for(int i = 0;i < WorldObjects.size();i++){
             delete WorldObjects.at(i);
         }
         WorldObjects.clear();
     }
     catch(const std::exception& e){
         std::cout << e.what() << '\n';
     }
     //delte textures
     try{
         for(int i = 0;i < WorldTextures.size();i++){
             delete WorldTextures.at(i);
         }
         WorldTextures.clear();
     }
     catch(const std::exception& e){
         std::cout << e.what() << '\n';
     }
     //delete shaders
     try{
         for(int i = 0;i < WorldShaders.size();i++){
             delete WorldShaders.at(i);
         }
         WorldShaders.clear();
     }
     catch(const std::exception& e){
         std::cout << e.what() << '\n';
     }
 }
Member Function Documentation
addObject()
int world::addObject (game_object * obj)
The addObject function will add an object to the world.
All added objects will be drawn on each world tick.
Definition at line 95 of file world.cpp.
References game_object::setScreenSize(), windowHeight, windowWidth, and WorldObjects.
{
     WorldObjects.emplace_back(obj);
     if(WorldObjects.back() == obj){
         obj->setScreenSize(windowWidth,windowHeight);
         return 0;
     }else{
         return -1;
     }
 }
addShader()
int world::addShader (shader * shade)
The addShader function will add a shader to the world.
Please add all shader you use for your objects to the world the objects resides in. Not doing this may easily cause NULL Pointer exceptions and Segmentation faults.
Definition at line 76 of file world.cpp.
References projectionMatrix, shader::setProjectionmatrix(), and WorldShaders.
{
     WorldShaders.emplace_back(shade);
     if(WorldShaders.back() == shade){
         shade->setProjectionmatrix(projectionMatrix);
         return 0;
     }else{
         return -1;
     }
 }
addTexture()
int world::addTexture (texture2D * tex)
The addTexture function will add a texture to the world.
Please add all testures you use for your objects to the world the objects resides in. Not doing this may easily cause NULL Pointer exceptions and Segmentation faults.
Definition at line 86 of file world.cpp.
References WorldTextures.
{
     WorldTextures.emplace_back(tex);
     if(WorldTextures.back() == tex){
         return 0;
     }else{
         return -1;
     }
 }
getObjectByName()
game_object * world::getObjectByName (std::string name)
This function returns a pointer to the first object with the given name.
Parameters
name the name of the wanted object
Returns
pointer to the object if everything worked, nullptr if no shader was found or something went wrong
Definition at line 197 of file world.cpp.
References WorldObjects.
{
     int i = 0;
     bool found = false;
     while(i < WorldObjects.size()){
         if((WorldObjects.at(i)->getName()).compare(name) == 0){
             found = true;
             break;
         }
         i++;
     }
     if(found){
         return WorldObjects.at(i);
     }else{
         return nullptr;
     }
 }
getShaderByName()
shader * world::getShaderByName (std::string name)
This function returns a pointer to the first shader with the given name.
Parameters
name the name of the wanted shader
Returns
pointer to the shader if everything worked, nullptr if no shader was found or something went wrong
Definition at line 158 of file world.cpp.
References WorldShaders.
{
     int i = 0;
     bool found = false;
     while(i < WorldShaders.size()){
         if((WorldShaders.at(i)->getName()).compare(name) == 0){
             found = true;
             break;
         }
         i++;
     }
     if(found){
         return WorldShaders.at(i);
     }else{
         return nullptr;
     }
 }
getTextureByName()
texture2D * world::getTextureByName (std::string name)
This function returns a pointer to the first texture with the given name.
Parameters
name the name of the wanted texture
Returns
pointer to the texture if everything worked, nullptr if no shader was found or something went wrong
Definition at line 178 of file world.cpp.
References WorldTextures.
{
     int i = 0;
     bool found = false;
     while(i < WorldTextures.size()){
         if((WorldTextures.at(i)->getName()).compare(name) == 0){
             found = true;
             break;
         }
         i++;
     }
     if(found){
         return WorldTextures.at(i);
     }else{
         return nullptr;
     }
 }
moveCamera()
void world::moveCamera (float delta_pos_x, float delta_pos_y)
This function is used to set the position of the camera.
All units are in world space cooridinates The camera postition will be applied to all shaders inside of this world
Parameters
delta_pos_x The amount the camera should move along the x-Axis
delta_pos_y The amount the camera should move along the y-Axis
Definition at line 226 of file world.cpp.
References cameraPosition, and WorldShaders.
{
     cameraPosition[0] += delta_pos_x;
     cameraPosition[1] += delta_pos_y;
     for(int i = 0;i < WorldShaders.size();i++){
         WorldShaders.at(i)->moveCamera(delta_pos_x, delta_pos_y);
     }
 }
removeObject()
int world::removeObject (game_object * obj)
This function removes an object from its world and delete the object.
Parameters
obj a pointer to the object which should be removed
Returns
0 if everything worked, 1 if no object was found, negative if something bad happened
Definition at line 141 of file world.cpp.
References WorldObjects.
{
     for(int i = 0; i < WorldObjects.size();i++){
         if(obj == WorldObjects.at(i)){
             WorldObjects.erase(WorldObjects.begin() + i);
             try{
                 delete obj;
             }
             catch(const std::exception& e){
                 std::cout << e.what() << '\n';
                 return -1;
             }
             return 0;
         }
     }
     return 1;
 }
removeShader()
int world::removeShader (shader * shade)
This function removes a shader from its world and delete the shader.
Parameters
shade a pointer to the shader which should be removed
Returns
0 if everything worked, 1 if no object was found, negative if something bad happened
Definition at line 105 of file world.cpp.
References WorldShaders.
{
     for(int i = 0; i < WorldShaders.size();i++){
         if(shade == WorldShaders.at(i)){
             WorldShaders.erase(WorldShaders.begin() + i);
             try{
                 delete shade;
             }
             catch(const std::exception& e){
                 std::cout << e.what() << '\n';
                 return -1;
             }
             return 0;
         }
     }
     return 1;
 }
removeTexture()
int world::removeTexture (texture2D * tex)
This function removes a texture from its world and delete the texture.
Parameters
tex a pointer to the texture which should be removed
Returns
0 if everything worked, 1 if no object was found, negative if something bad happened
Definition at line 123 of file world.cpp.
References WorldTextures.
{
     for(int i = 0; i < WorldTextures.size();i++){
         if(tex == WorldTextures.at(i)){
             WorldTextures.erase(WorldTextures.begin() + i);
             try{
                 delete tex;
             }
             catch(const std::exception& e){
                 std::cout << e.what() << '\n';
                 return -1;
             }
             return 0;
         }
     }
     return 1;
 }
setCamera()
void world::setCamera (float pos_x, float pos_y)
This function is used to set the position of the camera.
All units are in world space cooridinates. The camera postition will be applied to all shaders inside of this world
Parameters
pos_x The x coordinate of the camera
pos_y The y coordinate of the camera
Definition at line 217 of file world.cpp.
References cameraPosition, and WorldShaders.
{
     cameraPosition[0] = pos_x;
     cameraPosition[1] = pos_y;
     for(int i = 0;i < WorldShaders.size();i++){
         WorldShaders.at(i)->setCamera(cameraPosition[0], cameraPosition[1]);
     }
 }
setWindowSize()
void world::setWindowSize (int width, int height)
This functions sets the window size to construct the projection matrix.
Every time the window size changess this function should be called in order to prevent unwanted stretching of all the objects.
Parameters
width The width of the currently active window
height The height of the currently active window
Definition at line 57 of file world.cpp.
References projectionMatrix, windowHeight, windowWidth, WorldObjects, and WorldShaders.
{
     if(width != windowWidth || height != windowHeight){
         windowWidth = width;
         windowHeight = height;
         projectionMatrix = glm::ortho(-1.0f, (float) width / (float) height, -1.0f, (float) height / (float) width, -10.0f, 10.0f);
         for(int i = 0;i < WorldShaders.size();i++){
             WorldShaders.at(i)->setProjectionmatrix(projectionMatrix);
         }
         for(int i = 0;i < WorldObjects.size();i++){
             WorldObjects.at(i)->setScreenSize(width,height);
         }
     }
 }
tick()
void world::tick (GLFWwindow * window)
This function executes a world tick and is called for each frame.
All inputs are processed, the physics is calculated and all objects are rendered.
Parameters
window the current active window where everything will be rendered
Definition at line 48 of file world.cpp.
References WorldObjects.
{
     for(int i = 0; i < WorldObjects.size(); i++){
         WorldObjects.at(i)->onLoop(window);
         WorldObjects.at(i)->draw();
     }
 }
Member Data Documentation
cameraPosition
float world::cameraPosition[2] = {0.0f, 0.0f} private
This array holds the current camera Position.
Definition at line 19 of file world.hpp.
projectionMatrix
glm::mat4 world::projectionMatrix private
This variable holds the current projection matrix.
Definition at line 28 of file world.hpp.
windowHeight
int world::windowHeight = 200 private
This variable holds the height of the window in pixels.
Definition at line 25 of file world.hpp.
windowWidth
int world::windowWidth = 600 private
This variable holds the width of the window in pixels.
Definition at line 22 of file world.hpp.
WorldObjects
std::vector<game_object*> world::WorldObjects private
This vector holds all the game_objetcs in this world.
Definition at line 10 of file world.hpp.
WorldShaders
std::vector<shader*> world::WorldShaders private
This vector holds all the shaders in this world.
Definition at line 13 of file world.hpp.
WorldTextures
std::vector<texture2D*> world::WorldTextures private
This vector holds all the textures in this world.
Definition at line 16 of file world.hpp.
The documentation for this class was generated from the following files:
src/world.hpp
src/world.cpp