libredhand: redhand::shader Class Reference
redhand::shader Class Reference
#include <shader.hpp>
Public Member Functions
shader ()
This constructor creates a shader with the default vector and fragment shaders named "default".
~shader ()
Destroy the shader object and delete the shader program.
shader (std::string_view name)
This constructor creates a shader with a given name.
int createShaderFromFile (std::string_view vertexPath, std::string_view fragmentPath)
Create a Shader From a file.
int createShaderFromCode (std::string_view vertexSource, std::string_view fragmentSource)
Create a Shader From source Code.
int createDefaultShader ()
Initilizes the shader object with the default shader.
bool hasErrored ()
This function returns true if an error happend during the setup of the shader or the shader is not initilized.
void use ()
This function activates the shader and sets the camera position.
std::string_view getName ()
This function return the name the shader has.
unsigned int getID ()
This function returns the ID of the shader for the use in some OpenGL functions.
void setBool (const std::string &name, bool value) const
The setBool functions set a uniform vector of the shader to given values.
void setBool (const std::string &name, bool value, bool value2) const
The setBool functions set a uniform vector of the shader to given values.
void setBool (const std::string &name, bool value, bool value2, bool value3) const
The setBool functions set a uniform vector of the shader to given values.
void setBool (const std::string &name, bool value, bool value2, bool value3, bool value4) const
The setBool functions set a uniform vector of the shader to given values.
void setInt (const std::string &name, int value) const
The setInt functions set a uniform vector of the shader to given values.
void setInt (const std::string &name, int value, int value2) const
The setInt functions set a uniform vector of the shader to given values.
void setInt (const std::string &name, int value, int value2, int value3) const
The setInt functions set a uniform vector of the shader to given values.
void setInt (const std::string &name, int value, int value2, int value3, int value4) const
The setInt functions set a uniform vector of the shader to given values.
void setFloat (const std::string &name, float value) const
The setFloat functions set a uniform vector of the shader to given values.
void setFloat (const std::string &name, float value, float value2) const
The setFloat functions set a uniform vector of the shader to given values.
void setFloat (const std::string &name, float value, float value2, float value3) const
The setFloat functions set a uniform vector of the shader to given values.
void setFloat (const std::string &name, float value, float value2, float value3, float value4) const
The setFloat functions set a uniform vector of the shader to given values.
void getFloat (const std::string &name, float dest[]) const
This function gets a uniform float from an uniform vector and saves it to the destination.
void setCamera (float pos_x, float pos_y)
This function is used to set the position of the camera.
void moveCamera (float delta_pos_x, float delta_pos_y)
This function is used to set the position of the camera.
void setProjectionmatrix (glm::mat4 projection)
This function sets the projection matrix of the shader to the given matrix.
void setTextureScale (glm::vec2 scale)
This function sets the texture scale of the shader to the given vector.
Private Member Functions
std::string loadShaderCodeFromFile (std::string_view fileLocation)
This function basically just reads a file into a string.
unsigned int compileShader (std::string_view shaderCode, int shaderType)
This function compiles a given shader source code and returns the id of the compiled shader or 0 if there was an error.
void linkShader (unsigned int vertexShader, unsigned int fragmentShader)
This function links a vertex and fragment shader and if no error happened it will set initilized to true.
Private Attributes
unsigned int ID
the program ID
std::string shader_name = "shader"
the name of the shader
std::shared_mutex mutex_shader_name
the mutex for the shader_name
bool errord = false
true if an error happened
std::shared_mutex mutex_errord
the mutex for the errord
bool initilized = false
true if shader has been fully constructed
std::shared_mutex mutex_initilized
the mutex for the initilized
glm::vec3 cameraVector = glm::vec3(0.0f, 0.0f, 0.0f)
The position of the camera.
std::shared_mutex mutex_cameraVector
the mutex for the cameraVector
glm::mat4 camera = glm::mat4(1.0f)
The camera matrix.
std::shared_mutex mutex_camera
the mutex for the camera
glm::mat4 projectionMatrix
the projection matrix
std::shared_mutex mutex_projectionMatrix
the mutex for the projectionMatrix
glm::vec2 textureScale = glm::vec2(1.0f, 1.0f)
the texture scale
std::shared_mutex mutex_textureScale
the mutex for the texture scale
Detailed Description
Definition at line 22 of file shader.hpp.
Constructor & Destructor Documentation
shader() [1/2]
redhand::shader::shader ()
This constructor creates a shader with the default vector and fragment shaders named "default".
Definition at line 22 of file shader.cpp.
References createDefaultShader(), and errord.
~shader()
redhand::shader::~shader ()
Destroy the shader object and delete the shader program.
Definition at line 8 of file shader.cpp.
shader() [2/2]
redhand::shader::shader (std::string_view name)
This constructor creates a shader with a given name.
The default vertex and fragment shaders from the shaderSource.hpp will be used.
Parameters
name The name of the Shader
Definition at line 28 of file shader.cpp.
References shader_name.
Member Function Documentation
compileShader()
unsigned int redhand::shader::compileShader (std::string_view shaderCode, int shaderType) private
This function compiles a given shader source code and returns the id of the compiled shader or 0 if there was an error.
Definition at line 96 of file shader.cpp.
References errord, and shader().
createDefaultShader()
int redhand::shader::createDefaultShader ()
Initilizes the shader object with the default shader.
Returns
int negative value if anything went wrong
Definition at line 32 of file shader.cpp.
References createShaderFromCode(), redhand::DefaultFragmentSource, and redhand::DefaultVertexSource.
createShaderFromCode()
int redhand::shader::createShaderFromCode (std::string_view vertexSource, std::string_view fragmentSource)
Create a Shader From source Code.
Warning
make sure the location the string_view sees still has the string while the function is executed.
Parameters
vertexSource The source code of the vertex shader
fragmentSource The source code of the fragment shader
Returns
int
Definition at line 47 of file shader.cpp.
References compileShader(), FRAGMENT_SHADER, initilized, linkShader(), and VERTEX_SHADER.
createShaderFromFile()
int redhand::shader::createShaderFromFile (std::string_view vertexPath, std::string_view fragmentPath)
Create a Shader From a file.
Parameters
vertexPath The location of the vertex Shader
fragmentPath The location of the Fragment Shader
Returns
int negative if something went wrong
Definition at line 36 of file shader.cpp.
References createShaderFromCode(), and loadShaderCodeFromFile().
getFloat()
void redhand::shader::getFloat (const std::string & name, float dest[]) const
This function gets a uniform float from an uniform vector and saves it to the destination.
Parameters
name The name of the uniform variable
dest The array where the contents of the variables will be saved to
Definition at line 268 of file shader.cpp.
References ID.
getID()
unsigned int shader::getID ()
This function returns the ID of the shader for the use in some OpenGL functions.
Definition at line 182 of file shader.cpp.
References ID.
getName()
std::string_view redhand::shader::getName ()
This function return the name the shader has.
It will be "shader" if nothing else was specified.
Definition at line 204 of file shader.cpp.
References mutex_shader_name, and shader_name.
hasErrored()
bool redhand::shader::hasErrored ()
This function returns true if an error happend during the setup of the shader or the shader is not initilized.
Definition at line 173 of file shader.cpp.
References errord, initilized, mutex_errord, and mutex_initilized.
linkShader()
void redhand::shader::linkShader (unsigned int vertexShader, unsigned int fragmentShader) private
This function links a vertex and fragment shader and if no error happened it will set initilized to true.
Definition at line 123 of file shader.cpp.
References errord, ID, and initilized.
loadShaderCodeFromFile()
std::string redhand::shader::loadShaderCodeFromFile (std::string_view fileLocation) private
This function basically just reads a file into a string.
Definition at line 69 of file shader.cpp.
References errord.
moveCamera()
void redhand::shader::moveCamera (float delta_pos_x, float delta_pos_y)
This function is used to set the position of the camera.
All units are in world space cooridinates
Parameters
delta_pos_x The amount the camera should move along the x-Axis
delta_pos_y The amount the camera should move along the y-Axis
Definition at line 160 of file shader.cpp.
References camera, cameraVector, mutex_camera, and mutex_cameraVector.
setBool() [1/4]
void redhand::shader::setBool (const std::string & name, bool value) const
The setBool functions set a uniform vector of the shader to given values.
Parameters
name The name of the uniform variable
value The x component of the Vector
Definition at line 219 of file shader.cpp.
References ID.
setBool() [2/4]
void redhand::shader::setBool (const std::string & name, bool value, bool value2) const
The setBool functions set a uniform vector of the shader to given values.
Parameters
name The name of the uniform variable
value The x component of the Vector
value2 The y component of the Vector
Definition at line 222 of file shader.cpp.
References ID.
setBool() [3/4]
void redhand::shader::setBool (const std::string & name, bool value, bool value2, bool value3) const
The setBool functions set a uniform vector of the shader to given values.
Parameters
name The name of the uniform variable
value The x component of the Vector
value2 The y component of the Vector
value3 The z component of the Vector
Definition at line 226 of file shader.cpp.
References ID.
setBool() [4/4]
void redhand::shader::setBool (const std::string & name, bool value, bool value2, bool value3, bool value4) const
The setBool functions set a uniform vector of the shader to given values.
Parameters
name The name of the uniform variable
value The x component of the Vector
value2 The y component of the Vector
value3 The z component of the Vector
value4 The w component of the Vector
Definition at line 230 of file shader.cpp.
References ID.
setCamera()
void redhand::shader::setCamera (float pos_x, float pos_y)
This function is used to set the position of the camera.
All units are in world space cooridinates.
Parameters
pos_x The x coordinate of the camera
pos_y The y coordinate of the camera
Definition at line 147 of file shader.cpp.
References camera, cameraVector, mutex_camera, and mutex_cameraVector.
setFloat() [1/4]
void redhand::shader::setFloat (const std::string & name, float value) const
The setFloat functions set a uniform vector of the shader to given values.
Parameters
name The name of the uniform variable
value The x component of the Vector
Definition at line 252 of file shader.cpp.
References ID.
setFloat() [2/4]
void redhand::shader::setFloat (const std::string & name, float value, float value2) const
The setFloat functions set a uniform vector of the shader to given values.
Parameters
name The name of the uniform variable
value The x component of the Vector
value2 The y component of the Vector
Definition at line 256 of file shader.cpp.
References ID.
setFloat() [3/4]
void redhand::shader::setFloat (const std::string & name, float value, float value2, float value3) const
The setFloat functions set a uniform vector of the shader to given values.
Parameters
name The name of the uniform variable
value The x component of the Vector
value2 The y component of the Vector
value3 The z component of the Vector
Definition at line 260 of file shader.cpp.
References ID.
setFloat() [4/4]
void redhand::shader::setFloat (const std::string & name, float value, float value2, float value3, float value4) const
The setFloat functions set a uniform vector of the shader to given values.
Parameters
name The name of the uniform variable
value The x component of the Vector
value2 The y component of the Vector
value3 The z component of the Vector
value4 The w component of the Vector
Definition at line 264 of file shader.cpp.
References ID.
setInt() [1/4]
void redhand::shader::setInt (const std::string & name, int value) const
The setInt functions set a uniform vector of the shader to given values.
Parameters
name The name of the uniform variable
value The x component of the Vector
Definition at line 235 of file shader.cpp.
References ID.
setInt() [2/4]
void redhand::shader::setInt (const std::string & name, int value, int value2) const
The setInt functions set a uniform vector of the shader to given values.
Parameters
name The name of the uniform variable
value The x component of the Vector
value2 The y component of the Vector
Definition at line 239 of file shader.cpp.
References ID.
setInt() [3/4]
void redhand::shader::setInt (const std::string & name, int value, int value2, int value3) const
The setInt functions set a uniform vector of the shader to given values.
Parameters
name The name of the uniform variable
value The x component of the Vector
value2 The y component of the Vector
value3 The z component of the Vector
Definition at line 243 of file shader.cpp.
References ID.
setInt() [4/4]
void redhand::shader::setInt (const std::string & name, int value, int value2, int value3, int value4) const
The setInt functions set a uniform vector of the shader to given values.
Parameters
name The name of the uniform variable
value The x component of the Vector
value2 The y component of the Vector
value3 The z component of the Vector
value4 The w component of the Vector
Definition at line 247 of file shader.cpp.
References ID.
setProjectionmatrix()
void redhand::shader::setProjectionmatrix (glm::mat4 projection)
This function sets the projection matrix of the shader to the given matrix.
Parameters
projection the projection matrix which should be used
Definition at line 209 of file shader.cpp.
References mutex_projectionMatrix, and projectionMatrix.
setTextureScale()
void redhand::shader::setTextureScale (glm::vec2 scale)
This function sets the texture scale of the shader to the given vector.
Parameters
scale the texture scale which should be used
Definition at line 214 of file shader.cpp.
References mutex_textureScale, and textureScale.
use()
void redhand::shader::use ()
This function activates the shader and sets the camera position.
Definition at line 186 of file shader.cpp.
References camera, getID(), ID, mutex_camera, mutex_projectionMatrix, mutex_textureScale, projectionMatrix, setFloat(), and textureScale.
Member Data Documentation
camera
glm::mat4 redhand::shader::camera = glm::mat4(1.0f) private
The camera matrix.
Definition at line 48 of file shader.hpp.
cameraVector
glm::vec3 redhand::shader::cameraVector = glm::vec3(0.0f, 0.0f, 0.0f) private
The position of the camera.
Definition at line 43 of file shader.hpp.
errord
bool redhand::shader::errord = false private
true if an error happened
Definition at line 33 of file shader.hpp.
ID
unsigned int redhand::shader::ID private
the program ID
Definition at line 25 of file shader.hpp.
initilized
bool redhand::shader::initilized = false private
true if shader has been fully constructed
Definition at line 38 of file shader.hpp.
mutex_camera
std::shared_mutex redhand::shader::mutex_camera private
the mutex for the camera
Definition at line 50 of file shader.hpp.
mutex_cameraVector
std::shared_mutex redhand::shader::mutex_cameraVector private
the mutex for the cameraVector
Definition at line 45 of file shader.hpp.
mutex_errord
std::shared_mutex redhand::shader::mutex_errord private
the mutex for the errord
Definition at line 35 of file shader.hpp.
mutex_initilized
std::shared_mutex redhand::shader::mutex_initilized private
the mutex for the initilized
Definition at line 40 of file shader.hpp.
mutex_projectionMatrix
std::shared_mutex redhand::shader::mutex_projectionMatrix private
the mutex for the projectionMatrix
Definition at line 55 of file shader.hpp.
mutex_shader_name
std::shared_mutex redhand::shader::mutex_shader_name private
the mutex for the shader_name
Definition at line 30 of file shader.hpp.
mutex_textureScale
std::shared_mutex redhand::shader::mutex_textureScale private
the mutex for the texture scale
Definition at line 60 of file shader.hpp.
projectionMatrix
glm::mat4 redhand::shader::projectionMatrix private
the projection matrix
Definition at line 53 of file shader.hpp.
shader_name
std::string redhand::shader::shader_name = "shader" private
the name of the shader
Definition at line 28 of file shader.hpp.
textureScale
glm::vec2 redhand::shader::textureScale = glm::vec2(1.0f, 1.0f) private
the texture scale
Definition at line 58 of file shader.hpp.
The documentation for this class was generated from the following files:
include/redhand/shader.hpp
src/shader.cpp