libredhand: redhand::engine Class Reference
redhand::engine Class Reference
This class basically handles all the setup need for games to work.
#include <engine.hpp>
Public Member Functions
engine ()
The constructor for the engine which constructs the object.
~engine ()
The destructor for the engine which cleans everything up.
void setConfig (engine_config conf)
Set the Config of the game engine to the given configuration.
engine_config getConfig ()
Get the current configuration of the engine.
void init ()
This function initilizes the engine like specified in the configuration.
int changeWorld (std::shared_ptr< complex_world > newWorld)
change the world to the given new world
std::shared_ptr< complex_world > getActiveWorld ()
Get the Active World object.
GLFWwindow * getWindow ()
Get the Window object.
int getErrorCode ()
this function returns the error code
void clearBuffers ()
This functions clears the currently bound buffers.
void addGameLoopHandler (std::function< int(redhand::game_loop_event)> handle)
Add a new game_loop_event handler to the engine, to get called every game tick the handler_key is func.
void addGameLoopHandler (std::function< int(redhand::game_loop_event)> handle, std::string handler_key)
Add a new game_loop_event handler to the engine, to get called every game tick.
int removeGameLoopHandler (std::string handler_key)
remove a handler with a given key
int runGame ()
This function runs the game, the engine handles all the logic to keep everything wunning for you.
bool isRunning ()
returns true if the game is running
void stopGame (int error=0)
stops the game when called
Private Attributes
engine_config configuration
The opengl configuration of the engine.
GLFWwindow * window
a pointer to the active window
int errorCode = 0
an error code which hopefully stays 0 but will be negataiv if something bad happened
std::shared_ptr< complex_world > activeWorld
The currently active world (nullptr or empty world if none)
std::shared_ptr< complex_world > nextWorld
The next world that will be switched to in the next game tick.
std::unordered_multimap< std::string, std::function< int(redhand::game_loop_event)> > game_loop_handlers
std::shared_mutex runningReadMutex
bool running = false
Detailed Description
This class basically handles all the setup need for games to work.
Definition at line 24 of file engine.hpp.
Constructor & Destructor Documentation
engine()
redhand::engine::engine ()
The constructor for the engine which constructs the object.
Definition at line 13 of file engine.cpp.
~engine()
redhand::engine::~engine ()
The destructor for the engine which cleans everything up.
Definition at line 18 of file engine.cpp.
Member Function Documentation
addGameLoopHandler() [1/2]
void redhand::engine::addGameLoopHandler (std::function< int(redhand::game_loop_event)> handle)
Add a new game_loop_event handler to the engine, to get called every game tick the handler_key is func.
Note
The tick function of the current world is added by default.
Parameters
handle The function that should handle the game_loop_event raised by the engine.
Definition at line 107 of file engine.cpp.
addGameLoopHandler() [2/2]
void redhand::engine::addGameLoopHandler (std::function< int(redhand::game_loop_event)> handle, std::string handler_key)
Add a new game_loop_event handler to the engine, to get called every game tick.
Note
The tick function of the current world is added by default.
Parameters
handle The function that should handle the game_loop_event raised by the engine.
handler_key A handler_key of your choice except for "".
Definition at line 111 of file engine.cpp.
changeWorld()
int redhand::engine::changeWorld (std::shared_ptr< complex_world > newWorld)
change the world to the given new world
Version
Available since REDHAND_VERSION_NUMBER 1
Parameters
newWorld a shared pointer to the new world. An error will accour if it is a nullptr.
Returns
int
Definition at line 148 of file engine.cpp.
clearBuffers()
void redhand::engine::clearBuffers ()
This functions clears the currently bound buffers.
Version
Available since REDHAND_VERSION_NUMBER 1
Definition at line 94 of file engine.cpp.
getActiveWorld()
std::shared_ptr< redhand::complex_world > redhand::engine::getActiveWorld ()
Get the Active World object.
Version
Available since REDHAND_VERSION_NUMBER 1
Returns
std::shared_ptr<world> A pointer to the currently active world
Definition at line 86 of file engine.cpp.
getConfig()
redhand::engine_config redhand::engine::getConfig ()
Get the current configuration of the engine.
Version
Available since REDHAND_VERSION_NUMBER 1
Returns
engine_config The current configuration of the engine
Definition at line 33 of file engine.cpp.
getErrorCode()
int redhand::engine::getErrorCode ()
this function returns the error code
Version
Available since REDHAND_VERSION_NUMBER 1
Returns
negative if something bad happened
Definition at line 103 of file engine.cpp.
getWindow()
GLFWwindow * redhand::engine::getWindow ()
Get the Window object.
Warning
will be deprecated in the future only giving access to feautures over methods of the engine
Version
Available since REDHAND_VERSION_NUMBER 1
Returns
GLFWwindow* a pointer to the currently active window
Definition at line 99 of file engine.cpp.
init()
void redhand::engine::init ()
This function initilizes the engine like specified in the configuration.
Version
Available since REDHAND_VERSION_NUMBER 1
Definition at line 37 of file engine.cpp.
References redhand::framebuffer_size_callback(), redhand::input_system::getInstance(), redhand::initImageLoader(), and redhand::input_system::registerEngine().
isRunning()
bool redhand::engine::isRunning ()
returns true if the game is running
Version
Available since REDHAND_VERSION_NUMBER 1
Returns
true running
false not running
Definition at line 126 of file engine.cpp.
removeGameLoopHandler()
int redhand::engine::removeGameLoopHandler (std::string handler_key)
remove a handler with a given key
Parameters
handler_key the key of the function
Returns
int 0 if successful -1 if key not found
Definition at line 115 of file engine.cpp.
runGame()
int redhand::engine::runGame ()
This function runs the game, the engine handles all the logic to keep everything wunning for you.
Warning
This function runs until the game is finished and the game should terminate.
Version
Available since REDHAND_VERSION_NUMBER 1
Returns
int negative if something bad happend, otherwise a positive return code
Definition at line 164 of file engine.cpp.
setConfig()
void redhand::engine::setConfig (redhand::engine_config conf)
Set the Config of the game engine to the given configuration.
Version
Available since REDHAND_VERSION_NUMBER 1
Definition at line 28 of file engine.cpp.
References redhand::REDHAND_HEADER_VERSION, and redhand::engine_config::redhand_version.
stopGame()
void redhand::engine::stopGame (int error = 0)
stops the game when called
Version
Available since REDHAND_VERSION_NUMBER 1
Parameters
error the error code which the game should be set to, 0 if none is given.
Definition at line 138 of file engine.cpp.
Member Data Documentation
activeWorld
std::shared_ptr<complex_world> redhand::engine::activeWorld private
The currently active world (nullptr or empty world if none)
Definition at line 36 of file engine.hpp.
configuration
engine_config redhand::engine::configuration private
The opengl configuration of the engine.
Definition at line 27 of file engine.hpp.
errorCode
int redhand::engine::errorCode = 0 private
an error code which hopefully stays 0 but will be negataiv if something bad happened
Definition at line 33 of file engine.hpp.
game_loop_handlers
std::unordered_multimap<std::string, std::function<int(redhand::game_loop_event)> > redhand::engine::game_loop_handlers private
Definition at line 41 of file engine.hpp.
nextWorld
std::shared_ptr<complex_world> redhand::engine::nextWorld private
The next world that will be switched to in the next game tick.
Definition at line 39 of file engine.hpp.
running
bool redhand::engine::running = false private
Definition at line 45 of file engine.hpp.
runningReadMutex
std::shared_mutex redhand::engine::runningReadMutex private
Definition at line 43 of file engine.hpp.
window
GLFWwindow* redhand::engine::window private
a pointer to the active window
Definition at line 30 of file engine.hpp.
The documentation for this class was generated from the following files:
include/redhand/engine.hpp
src/engine.cpp