libredhand: redhand::input_system Class Reference
redhand::input_system Class Reference
#include <input.hpp>
Public Member Functions
void registerEngine (engine *main_engine)
key_actions getKeyAction (keyboard_keys wantedKey)
bool isKeyPressed (keyboard_keys wantedKey)
Static Public Member Functions
static input_system & getInstance ()
static key_actions static_getKeyAction (keyboard_keys wantedKey)
static bool static_isKeyPressed (keyboard_keys wantedKey)
static engine * getEngine ()
Private Member Functions
input_system (void)
input_system (input_system const &)
void operator= (input_system const &)
Private Attributes
engine * m_engine
Detailed Description
Definition at line 13 of file input.hpp.
Constructor & Destructor Documentation
input_system() [1/2]
redhand::input_system::input_system (void) inline private
Definition at line 16 of file input.hpp.
References operator=().
input_system() [2/2]
redhand::input_system::input_system (input_system const &) private
Member Function Documentation
getEngine()
static engine* redhand::input_system::getEngine () inline static
Definition at line 42 of file input.hpp.
References getInstance(), getKeyAction(), isKeyPressed(), m_engine, and registerEngine().
getInstance()
static input_system& redhand::input_system::getInstance () inline static
Definition at line 29 of file input.hpp.
getKeyAction()
redhand::key_actions redhand::input_system::getKeyAction (redhand::keyboard_keys wantedKey)
Definition at line 9 of file input.cpp.
References redhand::engine::getWindow(), m_engine, and redhand::UNKNOWN.
isKeyPressed()
bool redhand::input_system::isKeyPressed (redhand::keyboard_keys wantedKey)
Definition at line 17 of file input.cpp.
References getKeyAction(), and redhand::PRESS.
operator=()
void redhand::input_system::operator= (input_system const &) private
registerEngine()
void redhand::input_system::registerEngine (engine * main_engine)
Definition at line 5 of file input.cpp.
References m_engine.
static_getKeyAction()
static key_actions redhand::input_system::static_getKeyAction (keyboard_keys wantedKey) inline static
Definition at line 34 of file input.hpp.
References getInstance(), and getKeyAction().
static_isKeyPressed()
static bool redhand::input_system::static_isKeyPressed (keyboard_keys wantedKey) inline static
Definition at line 38 of file input.hpp.
References getInstance(), and isKeyPressed().
Member Data Documentation
m_engine
engine* redhand::input_system::m_engine private
Definition at line 24 of file input.hpp.
The documentation for this class was generated from the following files:
include/redhand/input.hpp
src/input.cpp