greenfoot++: object Class Reference
object Class Reference
#include <objects.hpp>
Public Member Functions
object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader *attached_shader, int gl_drawing_mode)
object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader *attached_shader, int gl_drawing_mode, std::function< void(shader *)> routine)
object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader *attached_shader, int gl_drawing_mode, std::vector< float > scaler, float rotator, std::vector< float > postitions)
object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader *attached_shader, int gl_drawing_mode, std::function< void(shader *)> routine, std::vector< float > scaler, float rotator, std::vector< float > postitions)
object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader *attached_shader, int gl_drawing_mode, std::function< void(shader *)> routine, std::vector< float > scaler, float rotator, std::vector< float > postitions, texture2D *texture)
object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader *attached_shader, int gl_drawing_mode, std::function< void(shader *)> routine, std::vector< float > scaler, float rotator, std::vector< float > postitions, texture2D *texture, std::vector< float > texels)
~object ()
void setShaderRoutine (std::function< void(shader *)> routine)
void setLoopFunction (std::function< void(GLFWwindow *window, object *obj)> loop)
shader * getShader ()
void draw ()
void onLoop (GLFWwindow *window)
bool hasErrord ()
std::vector< float > getPosition ()
void setPosition (std::vector< float > pos)
void move (std::vector< float > delta_pos)
float getRotation ()
void setRotation (float rot)
void rotate (float delta_rot)
void setColorAlpha (float alpha)
Detailed Description
Definition at line 17 of file objects.hpp.
Constructor & Destructor Documentation
object() [1/6]
object::object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader * attached_shader, int gl_drawing_mode)
Create arrays and buffers
Definition at line 4 of file objects.cpp.
object() [2/6]
object::object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader * attached_shader, int gl_drawing_mode, std::function< void(shader *)> routine)
Definition at line 63 of file objects.cpp.
object() [3/6]
object::object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader * attached_shader, int gl_drawing_mode, std::vector< float > scaler, float rotator, std::vector< float > postitions)
Definition at line 76 of file objects.cpp.
object() [4/6]
object::object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader * attached_shader, int gl_drawing_mode, std::function< void(shader *)> routine, std::vector< float > scaler, float rotator, std::vector< float > postitions)
Definition at line 98 of file objects.cpp.
object() [5/6]
object::object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader * attached_shader, int gl_drawing_mode, std::function< void(shader *)> routine, std::vector< float > scaler, float rotator, std::vector< float > postitions, texture2D * texture)
Definition at line 120 of file objects.cpp.
object() [6/6]
object::object (std::vector< float > points, std::vector< unsigned int > indices, std::vector< float > colors, shader * attached_shader, int gl_drawing_mode, std::function< void(shader *)> routine, std::vector< float > scaler, float rotator, std::vector< float > postitions, texture2D * texture, std::vector< float > texels)
Create arrays and buffers
Definition at line 142 of file objects.cpp.
~object()
object::~object ()
Definition at line 234 of file objects.cpp.
Member Function Documentation
draw()
void object::draw ()
Definition at line 240 of file objects.cpp.
References shader::getID(), shader::setFloat(), shader::setInt(), and shader::use().
getPosition()
std::vector< float > object::getPosition ()
Definition at line 303 of file objects.cpp.
getRotation()
float object::getRotation ()
Definition at line 318 of file objects.cpp.
getShader()
shader * object::getShader ()
Definition at line 299 of file objects.cpp.
hasErrord()
bool object::hasErrord ()
Definition at line 277 of file objects.cpp.
move()
void object::move (std::vector< float > delta_pos)
Definition at line 311 of file objects.cpp.
onLoop()
void object::onLoop (GLFWwindow * window)
Definition at line 287 of file objects.cpp.
References shader::use().
rotate()
void object::rotate (float delta_rot)
Definition at line 331 of file objects.cpp.
setColorAlpha()
void object::setColorAlpha (float alpha)
Definition at line 281 of file objects.cpp.
setLoopFunction()
void object::setLoopFunction (std::function< void(GLFWwindow *window, object *obj)> loop)
Definition at line 295 of file objects.cpp.
setPosition()
void object::setPosition (std::vector< float > pos)
Definition at line 307 of file objects.cpp.
setRotation()
void object::setRotation (float rot)
Definition at line 321 of file objects.cpp.
setShaderRoutine()
void object::setShaderRoutine (std::function< void(shader *)> routine)
Definition at line 292 of file objects.cpp.
The documentation for this class was generated from the following files:
src/objects.hpp
src/objects.cpp