redhand: redhand::world Class Reference
redhand::world Class Reference
#include <world.hpp>
Public Member Functions
world ()
The constructor will create an empty world which can be filled with objects.
~world ()
The destructor will clean up everything and delete all objects stored in this world.
int addShader (std::shared_ptr< redhand::shader >)
The addShader function will add a shader to the world.
int addTexture (texture2D *)
The addTexture function will add a texture to the world.
int addObject (game_object *)
The addObject function will add an object to the world.
int removeShader (std::string name)
This function removes a shader from its world and delete the shader.
int removeTexture (std::string name)
This function removes a texture from its world and delete the texture.
int removeObject (std::string name)
This function removes an object from its world and delete the object.
std::shared_ptr< redhand::shader > getShaderByName (std::string name)
This function returns a pointer to the first shader with the given name.
texture2D * getTextureByName (std::string name)
This function returns a pointer to the first texture with the given name.
game_object * getObjectByName (std::string name)
This function returns a pointer to the first object with the given name.
void tick (GLFWwindow *window)
This function executes a world tick and is called for each frame.
void setCamera (float pos_x, float pos_y)
This function is used to set the position of the camera.
void moveCamera (float delta_pos_x, float delta_pos_y)
This function is used to set the position of the camera.
void setWindowSize (int width, int height)
This functions sets the window size to construct the projection matrix.
void draw ()
draw all the objects in this world
Private Attributes
std::shared_mutex WorldObjectsMutex
The mutex for allowing only one thread to acces the world objects at once.
std::vector< game_object * > WorldObjects
This vector holds all the game_objetcs in this world.
std::vector< std::shared_ptr< redhand::shader > > WorldShaders
This vector holds all the shaders in this world.
std::vector< texture2D * > WorldTextures
This vector holds all the textures in this world.
float cameraPosition [2] = {0.0f, 0.0f}
This array holds the current camera Position.
int windowWidth = 600
This variable holds the width of the window in pixels.
int windowHeight = 200
This variable holds the height of the window in pixels.
glm::mat4 projectionMatrix
This variable holds the current projection matrix.
Detailed Description
Definition at line 10 of file world.hpp.
Constructor & Destructor Documentation
world()
redhand::world::world ()
The constructor will create an empty world which can be filled with objects.
Definition at line 5 of file world.cpp.
                    {
     WorldShaders = std::vector< std::shared_ptr<redhand::shader>>(0);
     WorldTextures = std::vector<texture2D*>(0);
     WorldObjects = std::vector<game_object*>(0);
     setWindowSize(600,600);
 }
~world()
redhand::world::~world ()
The destructor will clean up everything and delete all objects stored in this world.
Definition at line 13 of file world.cpp.
                     {
     WorldObjectsMutex.lock();
     //delete objects
     try{
         for(unsigned int i = 0;i < WorldObjects.size();i++){
             delete WorldObjects.at(i);
         }
         WorldObjects.clear();
     }
     catch(const std::exception& e){
         std::cout << e.what() << '\n';
     }
     //delte textures
     try{
         for(unsigned int i = 0;i < WorldTextures.size();i++){
             delete WorldTextures.at(i);
         }
         WorldTextures.clear();
     }
     catch(const std::exception& e){
         std::cout << e.what() << '\n';
     }
     //delete shaders
     try{
         for(auto x:WorldShaders){
             if (x.use_count() > 1){
                 std::cout << "still having references:" << x.use_count() << std::endl;
                 std::this_thread::sleep_for(std::chrono::milliseconds(1));
             }
             x.reset();
         }
         WorldShaders.clear();
     }
     catch(const std::exception& e){
         std::cout << e.what() << '\n';
     }
 }
Member Function Documentation
addObject()
int redhand::world::addObject (game_object * obj)
The addObject function will add an object to the world.
All added objects will be drawn on each world tick.
Definition at line 129 of file world.cpp.
References redhand::game_object::hasErrord(), and redhand::game_object::setScreenSize().
{
     if(obj == nullptr || obj == NULL){
         return -1;
     }
     if(obj->hasErrord()){
         return -2;
     }
     std::scoped_lock<std::shared_mutex> lock(WorldObjectsMutex);
     WorldObjects.emplace_back(obj);
     if(WorldObjects.back() == obj){
         obj->setScreenSize(windowWidth,windowHeight);
         return 0;
     }else{
         return -3;
     }
 }
addShader()
int redhand::world::addShader (std::shared_ptr< redhand::shader > shade)
The addShader function will add a shader to the world.
Please add all shader you use for your objects to the world the objects resides in. Not doing this may easily cause NULL Pointer exceptions and Segmentation faults.
Definition at line 93 of file world.cpp.
{
     if(shade == nullptr || shade == NULL){
         return -1;
     }
     if(shade->hasErrored()){
         return -2;
     }
     WorldShaders.emplace_back( std::shared_ptr<redhand::shader>(shade));
     if(WorldShaders.back() == shade){
         shade->setProjectionmatrix(projectionMatrix);
         shade->setCamera(cameraPosition[0], cameraPosition[1]);
         return 0;
     }else{
         return -4;
     }
 }
addTexture()
int redhand::world::addTexture (texture2D * tex)
The addTexture function will add a texture to the world.
Please add all testures you use for your objects to the world the objects resides in. Not doing this may easily cause NULL Pointer exceptions and Segmentation faults.
Definition at line 112 of file world.cpp.
References redhand::texture2D::hasErrord().
{
     if(tex == nullptr || tex == NULL){
         return -1;
     }
     if(tex->hasErrord()){
         return -2;
     }
     WorldTextures.emplace_back(tex);
     if(WorldTextures.back() == tex){
         return 0;
     }else{
         return -3;
     }
 }
draw()
void redhand::world::draw ()
draw all the objects in this world
Definition at line 63 of file world.cpp.
{
     std::shared_lock<std::shared_mutex> lock(WorldObjectsMutex);
     for(auto x : WorldObjects){
         x->draw();
     }
 }
getObjectByName()
game_object * redhand::world::getObjectByName (std::string name)
This function returns a pointer to the first object with the given name.
Parameters
name the name of the wanted object
Returns
pointer to the object if everything worked, nullptr if no shader was found or something went wrong
Definition at line 229 of file world.cpp.
{
     std::shared_lock<std::shared_mutex> lock(WorldObjectsMutex);
     for(auto x:WorldObjects){
         if(x->getName().compare(name) == 0){
             return x;
         }
     }
     return nullptr;
 }
getShaderByName()
std::shared_ptr< redhand::shader > redhand::world::getShaderByName (std::string name)
This function returns a pointer to the first shader with the given name.
Parameters
name the name of the wanted shader
Returns
pointer to the shader if everything worked, nullptr if no shader was found or something went wrong
Definition at line 204 of file world.cpp.
{
     for(auto x:WorldShaders){
        if((x->getName()).compare(name) == 0){
             return  std::shared_ptr<redhand::shader>(x);
         }
     }
     return nullptr;
 }
getTextureByName()
texture2D * redhand::world::getTextureByName (std::string name)
This function returns a pointer to the first texture with the given name.
Parameters
name the name of the wanted texture
Returns
pointer to the texture if everything worked, nullptr if no shader was found or something went wrong
Definition at line 216 of file world.cpp.
{
     for(auto x:WorldTextures){
        if((x->getName()).compare(name) == 0){
             return x;
         }
     }
     return nullptr;
 }
moveCamera()
void redhand::world::moveCamera (float delta_pos_x, float delta_pos_y)
This function is used to set the position of the camera.
All units are in world space cooridinates The camera postition will be applied to all shaders inside of this world
Parameters
delta_pos_x The amount the camera should move along the x-Axis
delta_pos_y The amount the camera should move along the y-Axis
Definition at line 251 of file world.cpp.
{
     cameraPosition[0] += delta_pos_x;
     cameraPosition[1] += delta_pos_y;
     for(auto x:WorldShaders){
         x->moveCamera(delta_pos_x, delta_pos_y);
     }
 }
removeObject()
int redhand::world::removeObject (std::string name)
This function removes an object from its world and delete the object.
Parameters
obj a pointer to the object which should be removed
Returns
0 if everything worked, 1 if no object was found, negative if something bad happened
Definition at line 184 of file world.cpp.
{
     std::scoped_lock<std::shared_mutex> lock(WorldObjectsMutex);
     for(auto x:WorldObjects){
         if(x->getName().compare(name) == 0){
             try{
                 delete x;
             }
             catch(const std::exception& e){
                 std::cerr << e.what() << '\n';
                 return -1;
             }
             return 0;
         }
     }
     return 1;
 }
removeShader()
int redhand::world::removeShader (std::string name)
This function removes a shader from its world and delete the shader.
Parameters
shade a pointer to the shader which should be removed
Returns
0 if everything worked, 1 if no object was found, negative if something bad happened
Definition at line 149 of file world.cpp.
{
     for(unsigned int i = 0; i < WorldShaders.size();i++){
         auto x = WorldShaders.at(i);
         if(x->getName().compare(name) == 0){
             try{
                 WorldShaders.erase(WorldShaders.begin() + i);
             }
             catch(const std::exception& e){
                 std::cerr << e.what() << '\n';
                 return -1;
             }
             return 0;
         }
     }
     return 1;
 }
removeTexture()
int redhand::world::removeTexture (std::string name)
This function removes a texture from its world and delete the texture.
Parameters
tex a pointer to the texture which should be removed
Returns
0 if everything worked, 1 if no object was found, negative if something bad happened
Definition at line 167 of file world.cpp.
{
     for(auto x:WorldTextures){
         if(x->getName().compare(name) == 0){
             try{
                 delete x;
             }
             catch(const std::exception& e){
                 std::cerr << e.what() << '\n';
                 return -1;
             }
             return 0;
         }
     }
     return 1;
 }
setCamera()
void redhand::world::setCamera (float pos_x, float pos_y)
This function is used to set the position of the camera.
All units are in world space cooridinates. The camera postition will be applied to all shaders inside of this world
Parameters
pos_x The x coordinate of the camera
pos_y The y coordinate of the camera
Definition at line 242 of file world.cpp.
{
     cameraPosition[0] = pos_x;
     cameraPosition[1] = pos_y;
     for(auto x : WorldShaders){
         x->setCamera(cameraPosition[0], cameraPosition[1]);
     }
 }
setWindowSize()
void redhand::world::setWindowSize (int width, int height)
This functions sets the window size to construct the projection matrix.
Every time the window size changess this function should be called in order to prevent unwanted stretching of all the objects.
Parameters
width The width of the currently active window
height The height of the currently active window
Definition at line 72 of file world.cpp.
{
     if(width != windowWidth || height != windowHeight){
         windowWidth = width;
         windowHeight = height;
         projectionMatrix = glm::ortho(-1.0f, (float) width / (float) height, -1.0f, (float) height / (float) width, -10.0f, 10.0f);
         for(unsigned int i = 0;i < WorldShaders.size();i++){
             WorldShaders.at(i)->setProjectionmatrix(projectionMatrix);
         }
         std::scoped_lock<std::shared_mutex> lock(WorldObjectsMutex);
         for(auto x:WorldObjects){
             x->setScreenSize(width,height);
         }
     }
 }
tick()
void redhand::world::tick (GLFWwindow * window)
This function executes a world tick and is called for each frame.
All inputs are processed, the physics is calculated and all objects are rendered.
Parameters
window the current active window where everything will be rendered
Definition at line 54 of file world.cpp.
{
     std::shared_lock<std::shared_mutex> lock(WorldObjectsMutex);
     for(auto x : WorldObjects){
         x->onLoop(window);
     }
 }
Member Data Documentation
cameraPosition
float redhand::world::cameraPosition[2] = {0.0f, 0.0f} private
This array holds the current camera Position.
Definition at line 25 of file world.hpp.
projectionMatrix
glm::mat4 redhand::world::projectionMatrix private
This variable holds the current projection matrix.
Definition at line 34 of file world.hpp.
windowHeight
int redhand::world::windowHeight = 200 private
This variable holds the height of the window in pixels.
Definition at line 31 of file world.hpp.
windowWidth
int redhand::world::windowWidth = 600 private
This variable holds the width of the window in pixels.
Definition at line 28 of file world.hpp.
WorldObjects
std::vector<game_object*> redhand::world::WorldObjects private
This vector holds all the game_objetcs in this world.
Definition at line 16 of file world.hpp.
WorldObjectsMutex
std::shared_mutex redhand::world::WorldObjectsMutex private
The mutex for allowing only one thread to acces the world objects at once.
Definition at line 13 of file world.hpp.
WorldShaders
std::vector< std::shared_ptr<redhand::shader> > redhand::world::WorldShaders private
This vector holds all the shaders in this world.
Definition at line 19 of file world.hpp.
WorldTextures
std::vector<texture2D*> redhand::world::WorldTextures private
This vector holds all the textures in this world.
Definition at line 22 of file world.hpp.
The documentation for this class was generated from the following files:
include/redhand/world.hpp
src/world.cpp