greenfoot++: src/game.cpp File Reference
game.cpp File Reference
#include "game.hpp"
Functions
int game_init (world *startWorld)
int game_loop (GLFWwindow *window, world *activeWorld, world *nextWorld)
int createTestworld (world *testWorld)
void processHouseMovement (GLFWwindow *window, object *obj)
void processGlobalInput (GLFWwindow *window)
Function Documentation
createTestworld()
int createTestworld (world * testWorld)
Definition at line 41 of file game.cpp.
References world::addObject(), world::addShader(), world::addTexture(), createCircle(), createHouse(), createRecktangle(), world::getObjectByIndex(), world::getShaderByName(), world::getTextureByIndex(), texture2D::getWidth(), processHouseMovement(), object::setLoopFunction(), object::setRotation(), and world::test().
game_init()
int game_init (world * startWorld)
Definition at line 3 of file game.cpp.
References createTestworld().
game_loop()
int game_loop (GLFWwindow * window, world * activeWorld, world * nextWorld)
Definition at line 16 of file game.cpp.
References processGlobalInput(), world::test(), and world::tick().
processGlobalInput()
void processGlobalInput (GLFWwindow * window)
Definition at line 192 of file game.cpp.
processHouseMovement()
void processHouseMovement (GLFWwindow * window, object * obj)
Definition at line 161 of file game.cpp.
References object::move(), and object::rotate().