redhand: src/game_object.hpp File Reference
game_object.hpp File Reference
#include "shader.hpp"
#include "texture.hpp"
#include "math.hpp"
#include <cmath>
#include <iostream>
#include <vector>
#include <functional>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glad/glad.h>
#include <GLFW/glfw3.h>
Classes
class game_object
The game_object is a simple object which can be displayed in a world.
Functions
game_object * createHouse (texture2D *texture, shader *shade, float texture_scale=1.0f)
Create a House object.
game_object * createCircle (float midpoint[2], float radius, int edges, float innerColor[3], float outerColor[3], shader *shade, texture2D *tex, float texture_scale=1.0f)
Create a Circle object.
game_object * createRecktangle (float bottomleft[2], float width, float height, float color[3], shader *shade, texture2D *tex, int DrawingMode, float textureScale=1.0f)
Create a rectangular object.
Function Documentation
createCircle()
game_object* createCircle (float midpoint[2], float radius, int edges, float innerColor[3], float outerColor[3], shader * shade, texture2D * tex, float texture_scale = 1.0f)
Create a Circle object.
Parameters
midpoint The midpoint of the circle in world coordinates
radius The radius of the circle in world scale
edges The number of edges the circle should have (more make it look more round but take more performance)
innerColor The inner color of the circle (rgb)
outerColor The outer color of the circle (rgb)
shade A pointer to the shader that should be used
tex A pointer to the texture that should be used (nullptr if none)
texture_scale The factor by which the texture shoulb be scaled (1.0f if nothig is specified)
Returns
game_object*
Definition at line 408 of file game_object.cpp.
References cosDeg(), game_object::game_object(), sinDeg(), and game_object::texture_scale.
  {
     std::vector <float> points = {0.5f, 0.5f};
     std::vector <unsigned int> indices;
     std::vector <float> colors = {1.0f, 1.0f, 0.0f};
     std::vector <float> texels = {0.5f*texture_scale, 0.5f*texture_scale};
     if(edges <= 2){
         edges = 120;
     }
     //Set default midpoint
     std::vector<float> position = {0.0f, 0.0f};
     if(midpoint != NULL){
         position.at(0) = midpoint[0]-0.5f*radius;
         position.at(1) = midpoint[1]-0.5f*radius;
     }
     //Set to yellow if NULL
     if(innerColor != NULL){
         for(int i = 0;i < 3;i++){
             colors.at(i) = innerColor[i];
         }
     }
     //Set to orange if NULL
     float oColor[3] = {1.0f, 0.3f, 0.0f};
     if(outerColor != NULL){
         for(int i = 0;i < 3;i++){
             oColor[i] = outerColor[i];
         }
     }
     for(int i = 0; i < edges;i++){
         float dx,dy;
         dx = cosDeg(i*360/edges)/2.0f + 0.5f;
         dy = sinDeg(i*360/edges)/2.0f + 0.5f;
         points.insert(points.end(), dx);
         points.insert(points.end(), dy);
         colors.insert(colors.end(), oColor[0]);
         colors.insert(colors.end(), oColor[1]);
         colors.insert(colors.end(), oColor[2]);
         texels.insert(texels.end(), dx*texture_scale);
         texels.insert(texels.end(), dy*texture_scale);
     }
     for(int i = 0;i < edges;i++){
         indices.insert(indices.end(), 0);
         indices.insert(indices.end(), i + 1);
         indices.insert(indices.end(), i + 2);
         if(indices.at(i*3 + 2) == edges + 1){indices.at(i*3 + 2) = 1;};
     }
     return new game_object(points, indices, colors, shade, GL_STATIC_DRAW, [](shader*){}, {radius,radius}, 0.0f, position, tex, texels);
 }
createHouse()
game_object* createHouse (texture2D * texture, shader * shade, float texture_scale = 1.0f)
Create a House object.
Parameters
texture A pointer to the texture that should be used (nullptr if none)
shade A pointer to the shader that should be used
texture_scale The factor by which the texture shoulb be scaled (1.0f if nothig is specified)
Returns
game_object*
Definition at line 370 of file game_object.cpp.
References game_object::game_object(), shader::setInt(), and game_object::texture_scale.
  {
     //Vertex Data
     std::vector <float> points = {
         1.0f, 0.55f,  // top right
         1.0f, 0.0f,  // bottom right
         0.0f, 0.0f,  // bottom left
         0.0f, 0.55f,  // top left
         0.5f, 1.0f,  // top middle
     };
     std::vector <unsigned int> indices = {
         0, 1, 3,   // first triangle
         1, 2, 3,    // second triangle
         0, 3, 4     //third triangle
     };
     std::vector <float> colors = {
         1.0f, 1.0f, 1.0f,
         1.0f, 1.0f, 1.0f,
         1.0f, 1.0f, 1.0f,
         1.0f, 1.0f, 1.0f,
         1.0f, 1.0f, 1.0f };
     std::vector <float> texels;
     for(int i = 0;i < points.size();i++){
         texels.emplace_back(points.at(i)*texture_scale);
     }
     std::function<void(shader*)> routine = [](shader* shade){
         shade->setInt("useTexture", 1);
     };
     return new game_object(points,indices,colors,shade,GL_DYNAMIC_DRAW,routine,{0.5f,0.5f},0.0f,{0.0f,0.0f},texture,texels);
 }
createRecktangle()
game_object* createRecktangle (float bottomleft[2], float width, float height, float color[3], shader * shade, texture2D * tex, int DrawingMode, float textureScale = 1.0f)
Create a rectangular object.
Parameters
bottomleft The position of the bottom left Corner in World Coordinates
width The width of the rectangle in World Coordinates
height The width of the rectangle in World Coordinates
color The color of the rectangle (rgb)
shade A pointer to the shader that should be used
tex A pointer to the texture that should be used (nullptr if none)
DrawingMode The GL_DRAWING_MODE that should be used (eg. GL_DYNAMIC_DRAW)
textureScale The factor by which the texture shoulb be scaled (1.0f if nothig is specified)
Returns
game_object*
Definition at line 477 of file game_object.cpp.
References game_object::game_object().
  {
     std::vector<float> points = {
         0.0f + 1.0f,  0.0f,        //top left
         0.0f + 1.0f,  0.0f + 1.0f, //top right
         0.0f,         0.0f + 1.0f, //bottom right
         0.0f,         0.0f         //bottom left
     };
     std::vector<unsigned int> indices = {
         0, 1, 2,   // first triangle
         0, 2, 3    // second triangle
     };
     std::vector<float> colors;
     for(int i = 0;i < 4;i++){
         colors.emplace_back(color[0]);
         colors.emplace_back(color[1]);
         colors.emplace_back(color[2]);
     }
     std::vector<float> texels = {
         1.0f,  0.0f, //top left
         1.0f,  1.0f, //top right
         0.0f,  1.0f, //bottom right
         0.0f,  0.0f  //bottom left
     };
     std::vector<float> position_vector = {bottomleft[0],bottomleft[1]};
     return new game_object(points,indices,colors,shade,DrawingMode,[](shader*){},{width,height},0.0f,position_vector,tex,texels);
 }