redhand: src/main.cpp File Reference
main.cpp File Reference
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <iostream>
#include <cmath>
#include <string>
#include <vector>
#include "game_object.hpp"
#include "shader.hpp"
#include "texture.hpp"
#include "game.hpp"
#include "world.hpp"
Functions
void framebuffer_size_callback (GLFWwindow *window, int width, int height)
void setWindowSize (int width, int height)
int main ()
Function Documentation
framebuffer_size_callback()
void framebuffer_size_callback (GLFWwindow * window, int width, int height)
Definition at line 136 of file main.cpp.
{
     glViewport(0, 0, width, height);
 }
main()
int main ()
Definition at line 26 of file main.cpp.
References framebuffer_size_callback(), game_init(), game_loop(), and initSTB().
           {
     int exitCode = 0;
     //initilize the engine and exit if error
     //init glfw
     glfwInit();
     glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
     glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
     glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
     //glfwWindowHint(GLFW_RESIZABLE, GL_FALSE);
     glfwWindowHint(GLFW_SAMPLES, 4);
     //glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE); //needed for mac
     //create window
     GLFWwindow* window = glfwCreateWindow(600, 600, "RedHand v0.0.1", NULL, NULL);
     if (window == NULL){
         std::cout << "Failed to create GLFW window" << std::endl;
         glfwTerminate();
         return -1;
     }
     glfwMakeContextCurrent(window);
     //register callback function for viewport
     glfwSetFramebufferSizeCallback(window, framebuffer_size_callback);
     //make sure glad works
     if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress)){
         std::cout << "Failed to initialize GLAD" << std::endl;
         return -2;
     }
     //init stb
     initSTB();
     //enable multisampling
     glEnable(GL_MULTISAMPLE);
     //Create the initial world
     world* activeWorld = new world();
     exitCode = game_init(activeWorld);
     if(exitCode < 0){
         glfwSetWindowShouldClose(window, true);
         exitCode = -3;
     };
     if(activeWorld == nullptr){
         glfwSetWindowShouldClose(window, true);
         exitCode = -4;
     }
     //Clear up
     glBindBuffer(GL_ARRAY_BUFFER, 0);
     glBindVertexArray(0);
     //render loop
     while(!glfwWindowShouldClose(window)){
         //run the game loop
         world* nextWorld = nullptr;
         exitCode = game_loop(window, activeWorld, nextWorld);
         //if egative return exit loop
         if(exitCode < 0){
             break;
         }
         //if !nullptr change world
         if(nextWorld != nullptr){
             try{
                 delete activeWorld;
             }
             catch(const std::exception& e){
                 std::cout << e.what() << '\n';
                 exitCode = -6;
                 break;
             }
             activeWorld = nextWorld;
         }
     }
     glfwSetWindowShouldClose(window, true);
     //try clearing up
     try{
         delete activeWorld;
     }
     catch(const std::exception& e){
         std::cerr << e.what() << '\n';
     }
     //close the window + clean up
     glfwTerminate();
     if(exitCode < 0){
         return -exitCode;
     }else{
         return exitCode;
     }
 }
setWindowSize()
void setWindowSize (int width, int height)
Definition at line 131 of file main.cpp.
{
     //glViewport(0, 0, width, height);
 }