# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/noa/opengl/greenfoot++

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/noa/opengl/greenfoot++

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/noa/opengl/greenfoot++/CMakeFiles /home/noa/opengl/greenfoot++/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/noa/opengl/greenfoot++/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named greenfoot++-mint-test

# Build rule for target.
greenfoot++-mint-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 greenfoot++-mint-test
.PHONY : greenfoot++-mint-test

# fast build rule for target.
greenfoot++-mint-test/fast:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/build
.PHONY : greenfoot++-mint-test/fast

src/game.o: src/game.cpp.o

.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i

.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s

.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/glad.o: src/glad.c.o

.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i

.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s

.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/objects.o: src/objects.cpp.o

.PHONY : src/objects.o

# target to build an object file
src/objects.cpp.o:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/objects.cpp.o
.PHONY : src/objects.cpp.o

src/objects.i: src/objects.cpp.i

.PHONY : src/objects.i

# target to preprocess a source file
src/objects.cpp.i:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/objects.cpp.i
.PHONY : src/objects.cpp.i

src/objects.s: src/objects.cpp.s

.PHONY : src/objects.s

# target to generate assembly for a file
src/objects.cpp.s:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/objects.cpp.s
.PHONY : src/objects.cpp.s

src/shader.o: src/shader.cpp.o

.PHONY : src/shader.o

# target to build an object file
src/shader.cpp.o:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/shader.cpp.o
.PHONY : src/shader.cpp.o

src/shader.i: src/shader.cpp.i

.PHONY : src/shader.i

# target to preprocess a source file
src/shader.cpp.i:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/shader.cpp.i
.PHONY : src/shader.cpp.i

src/shader.s: src/shader.cpp.s

.PHONY : src/shader.s

# target to generate assembly for a file
src/shader.cpp.s:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/shader.cpp.s
.PHONY : src/shader.cpp.s

src/texture.o: src/texture.cpp.o

.PHONY : src/texture.o

# target to build an object file
src/texture.cpp.o:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/texture.cpp.o
.PHONY : src/texture.cpp.o

src/texture.i: src/texture.cpp.i

.PHONY : src/texture.i

# target to preprocess a source file
src/texture.cpp.i:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/texture.cpp.i
.PHONY : src/texture.cpp.i

src/texture.s: src/texture.cpp.s

.PHONY : src/texture.s

# target to generate assembly for a file
src/texture.cpp.s:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/texture.cpp.s
.PHONY : src/texture.cpp.s

src/world.o: src/world.cpp.o

.PHONY : src/world.o

# target to build an object file
src/world.cpp.o:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/world.cpp.o
.PHONY : src/world.cpp.o

src/world.i: src/world.cpp.i

.PHONY : src/world.i

# target to preprocess a source file
src/world.cpp.i:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/world.cpp.i
.PHONY : src/world.cpp.i

src/world.s: src/world.cpp.s

.PHONY : src/world.s

# target to generate assembly for a file
src/world.cpp.s:
	$(MAKE) -f CMakeFiles/greenfoot++-mint-test.dir/build.make CMakeFiles/greenfoot++-mint-test.dir/src/world.cpp.s
.PHONY : src/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... greenfoot++-mint-test"
	@echo "... edit_cache"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/objects.o"
	@echo "... src/objects.i"
	@echo "... src/objects.s"
	@echo "... src/shader.o"
	@echo "... src/shader.i"
	@echo "... src/shader.s"
	@echo "... src/texture.o"
	@echo "... src/texture.i"
	@echo "... src/texture.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

