redhand: redhand Namespace Reference
redhand Namespace Reference
Classes
class engine
This class basically handles all the setup need for games to work.
struct engine_config
class game_object
The game_object is a simple object which can be displayed in a world.
class shader
class texture2D
class world
Functions
void framebuffer_size_callback (GLFWwindow *, int width, int height)
This function will be called every time the window size is changed.
game_object * createHouse (texture2D *texture, std::shared_ptr< redhand::shader > shade, float texture_scale=1.0f)
Create a House object.
game_object * createCircle (float midpoint[2], float radius, unsigned int edges, float innerColor[3], float outerColor[3], std::shared_ptr< redhand::shader > shade, texture2D *tex, float texture_scale=1.0f)
Create a Circle object.
game_object * createRecktangle (float bottomleft[2], float width, float height, float color[3], std::shared_ptr< redhand::shader > shade, texture2D *tex, int DrawingMode, float textureScale=1.0f)
Create a rectangular object.
float sinDeg (float deg)
This function calculates a sine with an angle in degrees.
float cosDeg (float deg)
This function calculates a cosine with an angle in degrees.
void initSTB ()
Variables
const engine_config DEFAULT_ENGINE_CONFIG
const char DefaultFragmentSource []
const char DefaultVertexSource []
Function Documentation
cosDeg()
float redhand::cosDeg (float deg)
This function calculates a cosine with an angle in degrees.
Parameters
deg The angle in Degrees
Returns
float The cosine of that angle
Definition at line 9 of file math.cpp.
{
     return std::cos(deg/180*3.1415);
 }
createCircle()
game_object * redhand::createCircle (float midpoint[2], float radius, unsigned int edges, float innerColor[3], float outerColor[3], std::shared_ptr< redhand::shader > shade, texture2D * tex, float texture_scale = 1.0f)
Create a Circle object.
Parameters
midpoint The midpoint of the circle in world coordinates
radius The radius of the circle in world scale
edges The number of edges the circle should have (more make it look more round but take more performance)
innerColor The inner color of the circle (rgb)
outerColor The outer color of the circle (rgb)
shade A pointer to the shader that should be used
tex A pointer to the texture that should be used (nullptr if none)
texture_scale The factor by which the texture shoulb be scaled (1.0f if nothig is specified)
Returns
game_object*
Definition at line 457 of file game_object.cpp.
References cosDeg(), redhand::game_object::game_object(), sinDeg(), and redhand::game_object::texture_scale.
  {
     std::vector <float> points = {0.5f, 0.5f};
     std::vector <unsigned int> indices;
     std::vector <float> colors = {1.0f, 1.0f, 0.0f};
     std::vector <float> texels = {0.5f*texture_scale, 0.5f*texture_scale};
     if(edges <= 2){
         edges = 120;
     }
     //Set default midpoint
     std::vector<float> position = {0.0f, 0.0f};
     if(midpoint != NULL){
         position.at(0) = midpoint[0]-0.5f*radius;
         position.at(1) = midpoint[1]-0.5f*radius;
     }
     //Set to yellow if NULL
     if(innerColor != NULL){
         for(int i = 0;i < 3;i++){
             colors.at(i) = innerColor[i];
         }
     }
     //Set to orange if NULL
     float oColor[3] = {1.0f, 0.3f, 0.0f};
     if(outerColor != NULL){
         for(int i = 0;i < 3;i++){
             oColor[i] = outerColor[i];
         }
     }
     for(unsigned int i = 0; i < edges;i++){
         float dx,dy;
         dx = cosDeg(i*360/edges)/2.0f + 0.5f;
         dy = sinDeg(i*360/edges)/2.0f + 0.5f;
         points.insert(points.end(), dx);
         points.insert(points.end(), dy);
         colors.insert(colors.end(), oColor[0]);
         colors.insert(colors.end(), oColor[1]);
         colors.insert(colors.end(), oColor[2]);
         texels.insert(texels.end(), dx*texture_scale);
         texels.insert(texels.end(), dy*texture_scale);
     }
     for(unsigned int i = 0;i < edges;i++){
         indices.insert(indices.end(), 0);
         indices.insert(indices.end(), i + 1);
         indices.insert(indices.end(), i + 2);
         if(indices.at(i*3 + 2) == edges + 1){indices.at(i*3 + 2) = 1;};
     }
     return new game_object(points, indices, colors, shade, GL_STATIC_DRAW, [](std::shared_ptr<redhand::shader>){}, {radius,radius}, 0.0f, position, tex, texels);
 }
createHouse()
game_object * redhand::createHouse (texture2D * texture, std::shared_ptr< redhand::shader > shade, float texture_scale = 1.0f)
Create a House object.
Parameters
texture A pointer to the texture that should be used (nullptr if none)
shade A pointer to the shader that should be used
texture_scale The factor by which the texture shoulb be scaled (1.0f if nothig is specified)
Returns
game_object*
Definition at line 422 of file game_object.cpp.
References redhand::game_object::game_object().
  {
     //Vertex Data
     std::vector <float> points = {
         1.0f, 0.55f,  // top right
         1.0f, 0.0f,  // bottom right
         0.0f, 0.0f,  // bottom left
         0.0f, 0.55f,  // top left
         0.5f, 1.0f,  // top middle
     };
     std::vector <unsigned int> indices = {
         0, 1, 3,   // first triangle
         1, 2, 3,    // second triangle
         0, 3, 4     //third triangle
     };
     std::vector <float> colors = {
         1.0f, 1.0f, 1.0f,
         1.0f, 1.0f, 1.0f,
         1.0f, 1.0f, 1.0f,
         1.0f, 1.0f, 1.0f,
         1.0f, 1.0f, 1.0f };
     std::vector <float> texels;
     for(auto x:points){
         texels.emplace_back(x*texture_scale);
     }
     return new game_object(points,indices,colors,shade,GL_DYNAMIC_DRAW,[](std::shared_ptr<redhand::shader>){},{0.5f,0.5f},0.0f,{0.0f,0.0f},texture,texels);
 }
createRecktangle()
game_object * redhand::createRecktangle (float bottomleft[2], float width, float height, float color[3], std::shared_ptr< redhand::shader > shade, texture2D * tex, int DrawingMode, float textureScale = 1.0f)
Create a rectangular object.
Parameters
bottomleft The position of the bottom left Corner in World Coordinates
width The width of the rectangle in World Coordinates
height The width of the rectangle in World Coordinates
color The color of the rectangle (rgb)
shade A pointer to the shader that should be used
tex A pointer to the texture that should be used (nullptr if none)
DrawingMode The GL_DRAWING_MODE that should be used (eg. GL_DYNAMIC_DRAW)
textureScale The factor by which the texture shoulb be scaled (1.0f if nothig is specified)
Returns
game_object*
Definition at line 526 of file game_object.cpp.
References redhand::game_object::game_object().
  {
     std::vector<float> points = {
         0.0f + 1.0f,  0.0f,        //top left
         0.0f + 1.0f,  0.0f + 1.0f, //top right
         0.0f,         0.0f + 1.0f, //bottom right
         0.0f,         0.0f         //bottom left
     };
     std::vector<unsigned int> indices = {
         0, 1, 2,   // first triangle
         0, 2, 3    // second triangle
     };
     std::vector<float> colors;
     for(int i = 0;i < 4;i++){
         colors.emplace_back(color[0]);
         colors.emplace_back(color[1]);
         colors.emplace_back(color[2]);
     }
     std::vector<float> texels = {
         1.0f,  0.0f, //top left
         1.0f,  1.0f, //top right
         0.0f,  1.0f, //bottom right
         0.0f,  0.0f  //bottom left
     };
     std::vector<float> position_vector = {bottomleft[0],bottomleft[1]};
     auto obj = new game_object(points,indices,colors,shade,DrawingMode,[](std::shared_ptr<redhand::shader>){},{width,height},0.0f,position_vector,tex,texels);
     return obj;
 }
framebuffer_size_callback()
void redhand::framebuffer_size_callback (GLFWwindow * , int width, int height)
This function will be called every time the window size is changed.
Definition at line 215 of file engine.cpp.
{
     glViewport(0, 0, width, height);
 }
initSTB()
void redhand::initSTB ()
Definition at line 11 of file texture.cpp.
                      {
     stbi_set_flip_vertically_on_load(true);
 }
sinDeg()
float redhand::sinDeg (float deg)
This function calculates a sine with an angle in degrees.
Parameters
deg The angle in Degrees
Returns
float The sine of that angle
Definition at line 5 of file math.cpp.
{
     return std::sin(deg/180*3.1415);
 }
Variable Documentation
DEFAULT_ENGINE_CONFIG
const engine_config redhand::DEFAULT_ENGINE_CONFIG
Initial value:
= {
    3,
    3,
    GLFW_OPENGL_CORE_PROFILE,
    4,
    GL_FALSE,
    GL_TRUE,
    600,
    600,
    REDHAND_VERSION_STRING
}
Definition at line 58 of file engine.hpp.
DefaultFragmentSource
const char redhand::DefaultFragmentSource[]
Initial value:
=
"#version 330 core\
\n \
\n out vec4 FragColor;\
\n \
\n in vec3 vertColor;\
\n in vec2 TexCoord;\
\n \
\n uniform int textureMode;\
\n uniform float colorAlpha;\
\n uniform vec2 textureScale;\
\n uniform sampler2D tex1;\
\n \
\n void main(){\
\n     if(textureMode == 1){\
\n         FragColor = texture(tex1, vec2(textureScale.x * TexCoord.x,textureScale.y * TexCoord.y)) * vec4(vertColor, colorAlpha);\
\n     }else{\
\n         FragColor = vec4(vertColor, colorAlpha);\
\n     }\
\n }\
\0"
Definition at line 5 of file shaderSource.hpp.
DefaultVertexSource
const char redhand::DefaultVertexSource[]
Initial value:
=
"#version 330 core\
\n \
\n layout (location = 0) in vec3 aPos;\
\n layout (location = 1) in vec3 aColor;\
\n layout (location = 2) in vec2 aTexCoord;\
\n \
\n out vec3 vertColor;\
\n out vec2 TexCoord;\
\n \
\n uniform mat4 worldTransformation;\
\n uniform mat4 camera;\
\n uniform mat4 projection;\
\n \
\n void main(){\
\n     gl_Position = projection * camera * worldTransformation * vec4(aPos.xyz, 1.0f);\
\n     vertColor = aColor;\
\n     TexCoord = aTexCoord;\
\n }\
\0"
Definition at line 27 of file shaderSource.hpp.