redhand: src/objects.hpp File Reference
objects.hpp File Reference
#include "shader.hpp"
#include "texture.hpp"
#include <cmath>
#include <iostream>
#include <vector>
#include <functional>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glad/glad.h>
#include <GLFW/glfw3.h>
Classes
class object
Functions
object * createHouse (texture2D *texture, shader *shade, float texture_scale=1.0f)
object * createCircle (float midpoint[2], float radius, int edges, float innerColor[3], float outerColor[3], shader *shade, texture2D *tex, float texture_scale=1.0f)
object * createRecktangle (float bottomleft[2], float width, float height, float color[3], shader *shade, texture2D *tex, int DrawingMode, float textureScale=1.0f)
float degToRad (float val)
float sinDeg (float deg)
float cosDeg (float deg)
Function Documentation
cosDeg()
float cosDeg (float deg)
Definition at line 518 of file objects.cpp.
References degToRad().
createCircle()
object* createCircle (float midpoint[2], float radius, int edges, float innerColor[3], float outerColor[3], shader * shade, texture2D * tex, float texture_scale = 1.0f)
Definition at line 397 of file objects.cpp.
References cosDeg(), object::object(), and sinDeg().
createHouse()
object* createHouse (texture2D * texture, shader * shade, float texture_scale = 1.0f)
Definition at line 359 of file objects.cpp.
References object::object(), and shader::setInt().
createRecktangle()
object* createRecktangle (float bottomleft[2], float width, float height, float color[3], shader * shade, texture2D * tex, int DrawingMode, float textureScale = 1.0f)
Definition at line 466 of file objects.cpp.
References object::object().
degToRad()
float degToRad (float val)
Definition at line 510 of file objects.cpp.
sinDeg()
float sinDeg (float deg)
Definition at line 514 of file objects.cpp.
References degToRad().