redhand: src/objects.cpp File Reference
objects.cpp File Reference
#include "objects.hpp"
Functions
object * createHouse (texture2D *texture, shader *shade, float texture_scale)
object * createCircle (float midpoint[2], float radius, int edges, float innerColor[3], float outerColor[3], shader *shade, texture2D *tex, float texture_scale)
object * createRecktangle (float bottomleft[2], float width, float height, float color[3], shader *shade, texture2D *tex, int DrawingMode, float textureScale)
float degToRad (float val)
float sinDeg (float deg)
float cosDeg (float deg)
Function Documentation
cosDeg()
float cosDeg (float deg)
Definition at line 518 of file objects.cpp.
References degToRad().
createCircle()
object* createCircle (float midpoint[2], float radius, int edges, float innerColor[3], float outerColor[3], shader * shade, texture2D * tex, float texture_scale)
Definition at line 397 of file objects.cpp.
References cosDeg(), object::object(), and sinDeg().
createHouse()
object* createHouse (texture2D * texture, shader * shade, float texture_scale)
Definition at line 359 of file objects.cpp.
References object::object(), and shader::setInt().
createRecktangle()
object* createRecktangle (float bottomleft[2], float width, float height, float color[3], shader * shade, texture2D * tex, int DrawingMode, float textureScale)
Definition at line 466 of file objects.cpp.
References object::object().
degToRad()
float degToRad (float val)
Definition at line 510 of file objects.cpp.
sinDeg()
float sinDeg (float deg)
Definition at line 514 of file objects.cpp.
References degToRad().