name: create automatic stable release

on:
  push:
    tags:
      - "v*"

jobs:
  pre-release:
    name: "Stable Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
      with: 
        lfs: true
    - name: install dependencies
      run:  bash scripts/dependencies.sh --ci
    - name: setup the project
      run:  bash scripts/setup.sh --ci
    - name: build library
      run:  bash scripts/build.sh -j 2 -o $GITHUB_SHA
    - name: build testgame
      run:  bash scripts/testgame.sh -j 2 -o "testgame-$GITHUB_SHA"
    - name: compress header files
      run: zip deploy/headers.zip include/redhand/**
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          deploy/libredhand.so
          deploy/headers.zip
